/**
 * 招聘管理 Mock 数据
 * 提供招聘职位、简历、面试、录用记录的模拟数据，用于开发环境后端不可用时的回退
 */
import type {
  RecruitmentPosition,
  Resume,
  InterviewRecord,
  HireRecord,
} from '../../types/hr/recruitment'
import { RecruitmentStatus, ResumeStatus } from '../../types/hr/recruitment'

/** 延迟函数，模拟网络请求 */
export function delay(ms = 300): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

// ============================================================
// Mock 数据 - 招聘职位
// ============================================================

export let mockPositionList: RecruitmentPosition[] = [
  {
    id: 'POS001',
    positionName: '川菜主厨',
    departmentId: 'dept-002',
    departmentName: '后厨部',
    headcount: 2,
    status: RecruitmentStatus.PUBLISHED,
    salaryRange: '12K-18K',
    educationRequirement: 'high_school',
    experienceRequirement: '5年以上川菜经验',
    jobDescription: '负责川菜菜品的研发与制作，把控后厨出品质量，培训后厨团队。',
    requirements: '精通川菜烹饪技艺，熟悉食品安全规范，有连锁餐饮经验优先。',
    publishDate: '2026-05-01',
    deadline: '2026-07-01',
    applicantCount: 8,
    hiredCount: 0,
    creatorName: '孙丽',
    createTime: '2026-04-28 09:00:00',
    updateTime: '2026-05-01 10:00:00',
  },
  {
    id: 'POS002',
    positionName: '前厅服务员',
    departmentId: 'dept-001',
    departmentName: '前厅部',
    headcount: 5,
    status: RecruitmentStatus.PUBLISHED,
    salaryRange: '4K-6K',
    educationRequirement: 'high_school',
    experienceRequirement: '不限',
    jobDescription: '负责餐厅前厅接待、点餐服务、桌面清洁及顾客引导工作。',
    requirements: '形象气质佳，沟通能力良好，有服务意识，能接受轮班工作制。',
    publishDate: '2026-04-28',
    deadline: '2026-06-28',
    applicantCount: 23,
    hiredCount: 1,
    creatorName: '孙丽',
    createTime: '2026-04-25 09:00:00',
    updateTime: '2026-05-20 14:00:00',
  },
  {
    id: 'POS003',
    positionName: '店长助理',
    departmentId: 'dept-003',
    departmentName: '管理部',
    headcount: 1,
    status: RecruitmentStatus.CLOSED,
    salaryRange: '8K-12K',
    educationRequirement: 'bachelor',
    experienceRequirement: '3年以上餐饮管理经验',
    jobDescription: '协助店长处理门店日常运营事务，包括人员调度、成本控制、客户关系维护。',
    requirements: '本科及以上学历，熟悉餐饮行业运营，具备较强的组织协调能力。',
    publishDate: '2026-04-10',
    deadline: '2026-05-10',
    applicantCount: 15,
    hiredCount: 1,
    creatorName: '陈刚',
    createTime: '2026-04-08 09:00:00',
    updateTime: '2026-05-15 16:00:00',
  },
  {
    id: 'POS004',
    positionName: '采购专员',
    departmentId: 'dept-006',
    departmentName: '采购部',
    headcount: 1,
    status: RecruitmentStatus.PUBLISHED,
    salaryRange: '5K-7K',
    educationRequirement: 'college',
    experienceRequirement: '2年以上采购经验',
    jobDescription: '负责食材、物料的采购工作，维护供应商关系，把控采购成本与质量。',
    requirements: '大专及以上学历，熟悉餐饮采购流程，具备良好的谈判能力。',
    publishDate: '2026-05-15',
    deadline: '2026-07-15',
    applicantCount: 6,
    hiredCount: 0,
    creatorName: '孙丽',
    createTime: '2026-05-12 09:00:00',
    updateTime: '2026-05-15 10:00:00',
  },
  {
    id: 'POS005',
    positionName: '财务主管',
    departmentId: 'dept-004',
    departmentName: '财务部',
    headcount: 1,
    status: RecruitmentStatus.DRAFT,
    salaryRange: '10K-15K',
    educationRequirement: 'bachelor',
    experienceRequirement: '5年以上财务工作经验',
    jobDescription: '负责公司财务核算、预算管理、税务申报及财务报表分析工作。',
    requirements: '财务、会计相关专业本科及以上学历，持有中级会计师资格证，熟悉餐饮行业财务。',
    deadline: '2026-08-01',
    applicantCount: 0,
    hiredCount: 0,
    creatorName: '陈刚',
    createTime: '2026-06-01 09:00:00',
    updateTime: '2026-06-01 09:00:00',
  },
  {
    id: 'POS006',
    positionName: '洗碗工',
    departmentId: 'dept-002',
    departmentName: '后厨部',
    headcount: 3,
    status: RecruitmentStatus.CANCELLED,
    salaryRange: '3.5K-4.5K',
    educationRequirement: 'none',
    experienceRequirement: '不限',
    jobDescription: '负责后厨餐具、厨具的清洗与消毒工作，保持后厨卫生整洁。',
    requirements: '身体健康，吃苦耐劳，有责任心。',
    publishDate: '2026-03-01',
    deadline: '2026-04-01',
    applicantCount: 4,
    hiredCount: 0,
    creatorName: '孙丽',
    createTime: '2026-02-28 09:00:00',
    updateTime: '2026-04-05 10:00:00',
  },
]

// ============================================================
// Mock 数据 - 简历
// ============================================================

export let mockResumeList: Resume[] = [
  {
    id: 'RES001',
    positionId: 'POS001',
    positionName: '川菜主厨',
    applicantName: '周大厨',
    phone: '13800138001',
    email: 'zhouchef@example.com',
    gender: 'male',
    age: 38,
    education: '高中',
    experience: '12年川菜烹饪经验，曾任多家知名川菜馆主厨',
    resumeUrl: '/resumes/zhou.pdf',
    status: ResumeStatus.INTERVIEWING,
    submitTime: '2026-05-05 10:30:00',
    remark: '经验丰富，作品集优秀',
  },
  {
    id: 'RES002',
    positionId: 'POS001',
    positionName: '川菜主厨',
    applicantName: '吴师傅',
    phone: '13800138002',
    email: 'wuchef@example.com',
    gender: 'male',
    age: 35,
    education: '高中',
    experience: '10年川菜经验，擅长创新菜品',
    status: ResumeStatus.SCREENING,
    submitTime: '2026-05-08 14:20:00',
  },
  {
    id: 'RES003',
    positionId: 'POS002',
    positionName: '前厅服务员',
    applicantName: '林小芳',
    phone: '13800138003',
    email: 'linxf@example.com',
    gender: 'female',
    age: 24,
    education: '大专',
    experience: '2年餐饮服务经验',
    status: ResumeStatus.HIRED,
    submitTime: '2026-05-02 09:15:00',
    remark: '形象气质佳，已入职',
  },
  {
    id: 'RES004',
    positionId: 'POS002',
    positionName: '前厅服务员',
    applicantName: '黄丽',
    phone: '13800138004',
    email: 'huangli@example.com',
    gender: 'female',
    age: 22,
    education: '高中',
    experience: '应届毕业生，有兼职服务经验',
    status: ResumeStatus.OFFERED,
    submitTime: '2026-05-10 11:00:00',
  },
  {
    id: 'RES005',
    positionId: 'POS002',
    positionName: '前厅服务员',
    applicantName: '赵强',
    phone: '13800138005',
    gender: 'male',
    age: 26,
    education: '大专',
    experience: '3年餐饮服务经验',
    status: ResumeStatus.INTERVIEWING,
    submitTime: '2026-05-12 16:30:00',
  },
  {
    id: 'RES006',
    positionId: 'POS003',
    positionName: '店长助理',
    applicantName: '钱经理',
    phone: '13800138006',
    email: 'qianjl@example.com',
    gender: 'male',
    age: 32,
    education: '本科',
    experience: '5年餐饮管理经验，熟悉门店运营',
    status: ResumeStatus.HIRED,
    submitTime: '2026-04-15 10:00:00',
    remark: '已入职，表现优秀',
  },
  {
    id: 'RES007',
    positionId: 'POS003',
    positionName: '店长助理',
    applicantName: '孙伟',
    phone: '13800138007',
    email: 'sunwei@example.com',
    gender: 'male',
    age: 30,
    education: '本科',
    experience: '4年餐饮管理经验',
    status: ResumeStatus.REJECTED,
    submitTime: '2026-04-18 14:00:00',
    remark: '面试表现一般，不符合岗位要求',
  },
  {
    id: 'RES008',
    positionId: 'POS004',
    positionName: '采购专员',
    applicantName: '李采购',
    phone: '13800138008',
    email: 'licg@example.com',
    gender: 'female',
    age: 28,
    education: '大专',
    experience: '3年餐饮采购经验，熟悉供应商管理',
    status: ResumeStatus.SUBMITTED,
    submitTime: '2026-05-16 09:30:00',
  },
  {
    id: 'RES009',
    positionId: 'POS004',
    positionName: '采购专员',
    applicantName: '王采购',
    phone: '13800138009',
    gender: 'male',
    age: 31,
    education: '本科',
    experience: '5年采购经验，持有采购师证书',
    status: ResumeStatus.SCREENING,
    submitTime: '2026-05-17 11:00:00',
  },
]

// ============================================================
// Mock 数据 - 面试记录
// ============================================================

export let mockInterviewList: InterviewRecord[] = [
  {
    id: 'INT001',
    resumeId: 'RES001',
    applicantName: '周大厨',
    positionName: '川菜主厨',
    interviewRound: 1,
    interviewType: 'phone',
    scheduledTime: '2026-05-10 14:00:00',
    duration: 30,
    interviewerName: '孙丽',
    result: 'pass',
    evaluation: '沟通流畅，对川菜理解深入，邀请现场试菜',
    createTime: '2026-05-09 10:00:00',
  },
  {
    id: 'INT002',
    resumeId: 'RES001',
    applicantName: '周大厨',
    positionName: '川菜主厨',
    interviewRound: 2,
    interviewType: 'onsite',
    scheduledTime: '2026-05-15 10:00:00',
    duration: 90,
    interviewerName: '陈刚',
    result: 'pending',
    remark: '现场试菜与技能考核',
    createTime: '2026-05-12 16:00:00',
  },
  {
    id: 'INT003',
    resumeId: 'RES003',
    applicantName: '林小芳',
    positionName: '前厅服务员',
    interviewRound: 1,
    interviewType: 'onsite',
    scheduledTime: '2026-05-05 15:00:00',
    duration: 30,
    interviewerName: '孙丽',
    result: 'pass',
    evaluation: '形象气质佳，服务意识强，符合岗位要求',
    createTime: '2026-05-03 09:00:00',
  },
  {
    id: 'INT004',
    resumeId: 'RES004',
    applicantName: '黄丽',
    positionName: '前厅服务员',
    interviewRound: 1,
    interviewType: 'video',
    scheduledTime: '2026-05-13 10:30:00',
    duration: 25,
    interviewerName: '孙丽',
    result: 'pass',
    evaluation: '态度积极，沟通良好，建议发offer',
    createTime: '2026-05-11 14:00:00',
  },
  {
    id: 'INT005',
    resumeId: 'RES005',
    applicantName: '赵强',
    positionName: '前厅服务员',
    interviewRound: 1,
    interviewType: 'onsite',
    scheduledTime: '2026-05-16 14:00:00',
    duration: 30,
    interviewerName: '孙丽',
    result: 'pending_next',
    evaluation: '经验丰富，需安排二面与店长沟通',
    createTime: '2026-05-14 10:00:00',
  },
  {
    id: 'INT006',
    resumeId: 'RES006',
    applicantName: '钱经理',
    positionName: '店长助理',
    interviewRound: 1,
    interviewType: 'onsite',
    scheduledTime: '2026-04-20 10:00:00',
    duration: 60,
    interviewerName: '陈刚',
    result: 'pass',
    evaluation: '管理思路清晰，对门店运营有独到见解',
    createTime: '2026-04-18 09:00:00',
  },
  {
    id: 'INT007',
    resumeId: 'RES006',
    applicantName: '钱经理',
    positionName: '店长助理',
    interviewRound: 2,
    interviewType: 'onsite',
    scheduledTime: '2026-04-25 14:00:00',
    duration: 60,
    interviewerName: '陈刚',
    result: 'pass',
    evaluation: '综合素质优秀，建议录用',
    createTime: '2026-04-22 16:00:00',
  },
]

// ============================================================
// Mock 数据 - 录用记录
// ============================================================

export let mockHireList: HireRecord[] = [
  {
    id: 'HIRE001',
    resumeId: 'RES003',
    applicantName: '林小芳',
    positionName: '前厅服务员',
    departmentName: '前厅部',
    offerDate: '2026-05-06',
    onboardDate: '2026-05-15',
    salary: 500000,
    status: 'onboarded',
    remark: '已顺利入职，表现良好',
    createTime: '2026-05-06 10:00:00',
  },
  {
    id: 'HIRE002',
    resumeId: 'RES006',
    applicantName: '钱经理',
    positionName: '店长助理',
    departmentName: '管理部',
    offerDate: '2026-04-26',
    onboardDate: '2026-05-05',
    salary: 1100000,
    status: 'onboarded',
    remark: '已入职，担任店长助理',
    createTime: '2026-04-26 15:00:00',
  },
  {
    id: 'HIRE003',
    resumeId: 'RES004',
    applicantName: '黄丽',
    positionName: '前厅服务员',
    departmentName: '前厅部',
    offerDate: '2026-05-14',
    onboardDate: '2026-05-25',
    salary: 450000,
    status: 'offered',
    remark: '等待候选人确认',
    createTime: '2026-05-14 11:00:00',
  },
]
