-- ============================================================
-- [DEPRECATED] 本文件为参考性 SQL，不再被项目使用
-- 项目实际使用 *DatabaseInitializer 模式（Java 代码建表）
-- 活跃迁移脚本位于 db/migration/V*.sql（Flyway 管理）
-- H2 环境使用 db/schema.sql + db/data.sql（spring.sql.init）
-- 财务模块使用 db/finance_tables.sql（FinanceDatabaseInitializer）
-- 请勿作为数据库初始化脚本引用
-- 标注时间：2026-06-30
-- ============================================================
CREATE TABLE IF NOT EXISTS `recruitment_requirements` (
  `id` VARCHAR(36) NOT NULL,
  `requirement_code` VARCHAR(50) NOT NULL,
  `position_name` VARCHAR(100) NOT NULL,
  `department_id` VARCHAR(36),
  `department_name` VARCHAR(100),
  `store_id` VARCHAR(36),
  `store_name` VARCHAR(100),
  `position_id` VARCHAR(36),
  `requirement_num` INT NOT NULL DEFAULT 1,
  `type` VARCHAR(20) NOT NULL DEFAULT 'hr',
  `status` VARCHAR(20) NOT NULL DEFAULT 'open',
  `approval_status` VARCHAR(20) DEFAULT 'approved',
  `description` TEXT,
  `requirements` TEXT,
  `salary_range` VARCHAR(50),
  `work_location` VARCHAR(200),
  `apply_deadline` DATETIME,
  `created_by` VARCHAR(36),
  `created_by_name` VARCHAR(50),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_requirement_code` (`requirement_code`),
  KEY `idx_department` (`department_id`),
  KEY `idx_store` (`store_id`),
  KEY `idx_status` (`status`),
  KEY `idx_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `resumes` (
  `id` VARCHAR(36) NOT NULL,
  `resume_code` VARCHAR(50) NOT NULL,
  `requirement_id` VARCHAR(36),
  `candidate_name` VARCHAR(50) NOT NULL,
  `gender` VARCHAR(10),
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100),
  `age` INT,
  `education` VARCHAR(50),
  `work_experience` INT,
  `current_salary` VARCHAR(50),
  `expected_salary` VARCHAR(50),
  `skills` TEXT,
  `experience` TEXT,
  `education_detail` TEXT,
  `self_introduction` TEXT,
  `attachment_url` VARCHAR(500),
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `source` VARCHAR(20) DEFAULT 'online',
  `created_by` VARCHAR(36),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_resume_code` (`resume_code`),
  KEY `idx_requirement` (`requirement_id`),
  KEY `idx_phone` (`phone`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `interviews` (
  `id` VARCHAR(36) NOT NULL,
  `interview_code` VARCHAR(50) NOT NULL,
  `resume_id` VARCHAR(36) NOT NULL,
  `requirement_id` VARCHAR(36),
  `interview_round` VARCHAR(20) NOT NULL,
  `interview_type` VARCHAR(20) DEFAULT 'offline',
  `interview_date` DATETIME NOT NULL,
  `interview_location` VARCHAR(200),
  `interviewer_id` VARCHAR(36),
  `interviewer_name` VARCHAR(50),
  `status` VARCHAR(20) NOT NULL DEFAULT 'scheduled',
  `result` VARCHAR(20),
  `score` INT,
  `feedback` TEXT,
  `notes` TEXT,
  `created_by` VARCHAR(36),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_interview_code` (`interview_code`),
  KEY `idx_resume` (`resume_id`),
  Key `idx_requirement` (`requirement_id`),
  KEY `idx_interviewer` (`interviewer_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `onboarding_records` (
  `id` VARCHAR(36) NOT NULL,
  `onboarding_code` VARCHAR(50) NOT NULL,
  `resume_id` VARCHAR(36) NOT NULL,
  `requirement_id` VARCHAR(36),
  `employee_id` VARCHAR(36),
  `employee_code` VARCHAR(50),
  `candidate_name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `department_id` VARCHAR(36),
  `department_name` VARCHAR(100),
  `store_id` VARCHAR(36),
  `store_name` VARCHAR(100),
  `position_id` VARCHAR(36),
  `position_name` VARCHAR(100),
  `hire_date` DATE NOT NULL,
  `probation_start` DATE,
  `probation_end` DATE,
  `probation_months` INT,
  `salary` DECIMAL(10,2),
  `registration_code` VARCHAR(50),
  `registration_code_status` VARCHAR(20) DEFAULT 'UNUSED',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `notes` TEXT,
  `created_by` VARCHAR(36),
  `created_by_name` VARCHAR(50),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_onboarding_code` (`onboarding_code`),
  KEY `idx_resume` (`resume_id`),
  KEY `idx_employee` (`employee_id`),
  KEY `idx_registration_code` (`registration_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
