-- ============================================================
-- V20260723_002__fix_users_identity_generation.sql
-- 修复 users.user_id 标识列生成策略
--
-- 问题：users.user_id 当前为 GENERATED ALWAYS AS IDENTITY，
--       但 User 实体使用 MyBatis-Plus IdType.ASSIGN_ID 雪花算法显式赋值，
--       PostgreSQL 拒绝非 DEFAULT 值插入，导致真实验收测试员工账号初始化失败。
--
-- 修复：将 user_id 改为 GENERATED BY DEFAULT AS IDENTITY，
--       既保留自动递增能力，又允许 BaseDatabaseInitializer 手动插入 admin(user_id=1)
--       及 MyBatis-Plus ASSIGN_ID 显式写入雪花 ID。
-- 幂等性：仅在当前策略为 ALWAYS 时执行 ALTER。
-- ============================================================

DO $$
DECLARE
    v_current_generation VARCHAR(10);
BEGIN
    SELECT identity_generation
    INTO v_current_generation
    FROM information_schema.columns
    WHERE table_name = 'users'
      AND column_name = 'user_id'
      AND is_identity = 'YES';

    IF v_current_generation = 'ALWAYS' THEN
        ALTER TABLE users ALTER COLUMN user_id SET GENERATED BY DEFAULT;
    END IF;
END $$;

-- 重置 identity 序列起始值，避免未来使用数据库自增时出现主键冲突
DO $$
DECLARE
    v_max_id BIGINT;
    v_seq_name TEXT;
BEGIN
    SELECT MAX(user_id) INTO v_max_id FROM users;
    IF v_max_id IS NOT NULL THEN
        SELECT pg_get_serial_sequence('users', 'user_id') INTO v_seq_name;
        IF v_seq_name IS NOT NULL THEN
            PERFORM setval(v_seq_name, v_max_id + 1, false);
        END IF;
    END IF;
END $$;
