package com.foodtraceability.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.Version;
import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;


/**
 * 凭证头实体类
 * @author example
 * @since 2025-12-06
 */
@TableName("voucher_header")
public class VoucherHeader implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 凭证ID
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * 凭证编号
     */
    @TableField("voucher_no")
    private String voucherNo;

    /**
     * 凭证日期
     */
    @TableField("voucher_date")
    private LocalDate voucherDate;

    /**
     * 凭证摘要
     */
    @TableField("summary")
    private String summary;

    /**
     * 会计期间（格式：YYYY-MM）
     */
    @TableField("period")
    private String period;

    /**
     * 借方合计
     */
    @TableField("total_debit")
    private BigDecimal totalDebit;

    /**
     * 贷方合计
     */
    @TableField("total_credit")
    private BigDecimal totalCredit;

    /**
     * 凭证状态：DRAFT(草稿)、SUBMITTED(已提交)、APPROVED(已审核)、POSTED(已记账)、CANCELLED(已作废)
     */
    @TableField("status")
    private String status;

    /**
     * 来源类型：MANUAL(手工)/AUTO_POS(POS自动)/AUTO_PURCHASE(采购自动)/AUTO_SETTLE(结算自动)/AUTO_PERIOD_END(期末自动)
     */
    @TableField("source_type")
    private String sourceType;

    /**
     * 来源业务单据ID
     */
    @TableField("source_business_id")
    private String sourceBusinessId;

    /**
     * 来源业务单据编号
     */
    @TableField("source_business_no")
    private String sourceBusinessNo;

    /**
     * 是否自动生成（0=手工/1=自动）
     */
    @TableField("auto_generated")
    private Boolean autoGenerated;

    /**
     * 质量评分（0-100，NULL=未评分）
     */
    @TableField("quality_score")
    private Integer qualityScore;

    /**
     * 审核状态：PENDING/APPROVED/REJECTED
     */
    @TableField("review_status")
    private String reviewStatus;

    /**
     * 审核人ID
     */
    @TableField("reviewer_id")
    private Long reviewerId;

    /**
     * 审核时间
     */
    @TableField("review_time")
    private LocalDateTime reviewTime;

    /**
     * 审核备注
     */
    @TableField("review_remark")
    private String reviewRemark;

    /**
     * 创建时间
     */
    @TableField("create_time")
    private LocalDateTime createTime;

    /**
     * 更新时间
     */
    @TableField("update_time")
    private LocalDateTime updateTime;

    /**
     * 创建人
     */
    @TableField("create_by")
    private String createBy;

    /**
     * 更新人
     */
    @TableField("update_by")
    private String updateBy;

    /**
     * 逻辑删除标记：0未删除，1已删除
     * 会计法合规：财务凭证禁止物理删除，仅允许逻辑删除（归档）
     */
    @TableLogic
    @TableField("deleted")
    private Integer deleted;

    /**
     * 乐观锁版本号
     * 防止凭证被并发篡改，违反会计法"凭证不得变造"
     */
    @Version
    @TableField("version")
    private Integer version;

    /**
     * 是否红冲凭证（FALSE=正常凭证，TRUE=红字冲销凭证）
     * 红字凭证用于冲销原凭证，金额取负数
     */
    @TableField("is_reversed")
    private Boolean isReversed;

    /**
     * 红冲原凭证ID（仅红字凭证有值，指向被冲销的原凭证）
     */
    @TableField("reverse_original_id")
    private Long reverseOriginalId;

    /**
     * 红冲原因（红字凭证必填，说明冲销原因）
     */
    @TableField("reverse_reason")
    private String reverseReason;

    /**
     * 凭证行列表（非数据库字段，用于返回结果时携带凭证行）
     */
    @TableField(exist = false)
    private List<VoucherLine> children;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVoucherNo() {
        return voucherNo;
    }

    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo;
    }

    public LocalDate getVoucherDate() {
        return voucherDate;
    }

    public void setVoucherDate(LocalDate voucherDate) {
        this.voucherDate = voucherDate;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getPeriod() {
        return period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public BigDecimal getTotalDebit() {
        return totalDebit;
    }

    public void setTotalDebit(BigDecimal totalDebit) {
        this.totalDebit = totalDebit;
    }

    public BigDecimal getTotalCredit() {
        return totalCredit;
    }

    public void setTotalCredit(BigDecimal totalCredit) {
        this.totalCredit = totalCredit;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getSourceBusinessId() {
        return sourceBusinessId;
    }

    public void setSourceBusinessId(String sourceBusinessId) {
        this.sourceBusinessId = sourceBusinessId;
    }

    public String getSourceBusinessNo() {
        return sourceBusinessNo;
    }

    public void setSourceBusinessNo(String sourceBusinessNo) {
        this.sourceBusinessNo = sourceBusinessNo;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Integer getQualityScore() {
        return qualityScore;
    }

    public void setQualityScore(Integer qualityScore) {
        this.qualityScore = qualityScore;
    }

    public String getReviewStatus() {
        return reviewStatus;
    }

    public void setReviewStatus(String reviewStatus) {
        this.reviewStatus = reviewStatus;
    }

    public Long getReviewerId() {
        return reviewerId;
    }

    public void setReviewerId(Long reviewerId) {
        this.reviewerId = reviewerId;
    }

    public LocalDateTime getReviewTime() {
        return reviewTime;
    }

    public void setReviewTime(LocalDateTime reviewTime) {
        this.reviewTime = reviewTime;
    }

    public String getReviewRemark() {
        return reviewRemark;
    }

    public void setReviewRemark(String reviewRemark) {
        this.reviewRemark = reviewRemark;
    }

    public LocalDateTime getCreateTime() {
        return createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Boolean getIsReversed() {
        return isReversed;
    }

    public void setIsReversed(Boolean isReversed) {
        this.isReversed = isReversed;
    }

    public Long getReverseOriginalId() {
        return reverseOriginalId;
    }

    public void setReverseOriginalId(Long reverseOriginalId) {
        this.reverseOriginalId = reverseOriginalId;
    }

    public String getReverseReason() {
        return reverseReason;
    }

    public void setReverseReason(String reverseReason) {
        this.reverseReason = reverseReason;
    }

    public List<VoucherLine> getChildren() {
        return children;
    }

    public void setChildren(List<VoucherLine> children) {
        this.children = children;
    }

    @Override
    public String toString() {
        return "VoucherHeader{" +
            "id=" + id +
            ", voucherNo='" + voucherNo + '\'' +
            ", voucherDate=" + voucherDate +
            ", summary='" + summary + '\'' +
            ", period='" + period + '\'' +
            ", totalDebit=" + totalDebit +
            ", totalCredit=" + totalCredit +
            ", status='" + status + '\'' +
            ", reviewStatus='" + reviewStatus + '\'' +
            ", isReversed=" + isReversed +
            ", reverseOriginalId=" + reverseOriginalId +
            ", createTime=" + createTime +
            ", updateTime=" + updateTime +
            ", createBy='" + createBy + '\'' +
            ", updateBy='" + updateBy + '\'' +
            ", deleted=" + deleted +
            ", version=" + version +
            ", children=" + children +
            '}';
    }
}
