<script setup lang="ts">
/**
 * 合同变更对话框
 * 支持3种变更类型：岗位/部门变更、合同期限变更、补充协议
 * 流程：填写变更信息 → 预览变更对比 → 提交创建
 */
import { ref, computed, watch } from 'vue'
import { ElMessage } from 'element-plus'
import StatusTag from '@/components/core/StatusTag.vue'
import ContentCard from '@/components/core/ContentCard.vue'
import { contractApi } from '@/api/hr/contract'
import type { EmployeeContract, ContractChangeType, ContractChangeDetail } from '@/types/hr/contract'
import { ContractChangeTypeOptions, ContractChangeTypeTagMap } from '@/types/hr/contract'

const props = defineProps<{
  visible: boolean
  contract: EmployeeContract | null
  changeType: ContractChangeType
}>()

const emit = defineEmits<{
  'update:visible': [value: boolean]
  'success': []
}>()

/* ===== 步骤控制 ===== */
const currentStep = ref(0)
const steps = [
  { title: '填写变更', description: '变更信息' },
  { title: '变更对比', description: '确认变更内容' },
  { title: '提交创建', description: '生成变更记录' },
]

/* ===== 表单数据 ===== */
const changeForm = ref({
  title: '',
  reason: '',
  effectiveDate: '',
  autoGenerateDocument: true,
})

// 岗位/部门变更字段
const positionChangeFields = ref({
  newDepartmentName: '',
  newPositionName: '',
  newWorkLocation: '',
})

// 期限变更字段
const termChangeFields = ref({
  newEndDate: '',
  newTermType: '' as string,
})

// 补充协议字段
const supplementaryContent = ref('')

const formLoading = ref(false)
const submitLoading = ref(false)

/* ===== 变更类型标签 ===== */
const changeTypeLabel = computed(() => {
  return ContractChangeTypeOptions.find(o => o.value === props.changeType)?.label || ''
})

/* ===== 自动生成标题 ===== */
watch(() => props.changeType, (type) => {
  if (!props.contract) return
  const empName = props.contract.employeeName
  if (type === 'position_change') {
    changeForm.value.title = `${empName}岗位变更协议`
  } else if (type === 'term_change') {
    changeForm.value.title = `${empName}合同期限变更协议`
  } else {
    changeForm.value.title = `${empName}补充协议`
  }
}, { immediate: true })

/* ===== 构建变更详情 ===== */
function buildChangeDetails(): ContractChangeDetail[] {
  if (!props.contract) return []
  const details: ContractChangeDetail[] = []

  if (props.changeType === 'position_change') {
    if (positionChangeFields.value.newDepartmentName && positionChangeFields.value.newDepartmentName !== props.contract.departmentName) {
      details.push({
        field: 'departmentName',
        fieldLabel: '部门',
        beforeValue: props.contract.departmentName || '-',
        afterValue: positionChangeFields.value.newDepartmentName,
      })
    }
    if (positionChangeFields.value.newPositionName && positionChangeFields.value.newPositionName !== props.contract.positionName) {
      details.push({
        field: 'positionName',
        fieldLabel: '职位',
        beforeValue: props.contract.positionName || '-',
        afterValue: positionChangeFields.value.newPositionName,
      })
    }
    if (positionChangeFields.value.newWorkLocation) {
      details.push({
        field: 'workLocation',
        fieldLabel: '工作地点',
        beforeValue: (props.contract as unknown as Record<string, unknown>).workLocation as string || '-',
        afterValue: positionChangeFields.value.newWorkLocation,
      })
    }
  } else if (props.changeType === 'term_change') {
    if (termChangeFields.value.newEndDate !== undefined) {
      details.push({
        field: 'endDate',
        fieldLabel: '到期日期',
        beforeValue: props.contract.endDate || '无固定期限',
        afterValue: termChangeFields.value.newEndDate || '无固定期限',
      })
    }
    if (termChangeFields.value.newTermType) {
      details.push({
        field: 'termType',
        fieldLabel: '期限类型',
        beforeValue: props.contract.termType || '-',
        afterValue: termChangeFields.value.newTermType,
      })
    }
  } else {
    // 补充协议
    details.push({
      field: 'supplementaryContent',
      fieldLabel: '补充内容',
      beforeValue: '-',
      afterValue: supplementaryContent.value,
    })
  }

  return details
}

/* ===== 变更详情（步骤2预览用） ===== */
const previewDetails = computed(() => buildChangeDetails())

/* ===== 步骤校验 ===== */
const canNext = computed(() => {
  if (currentStep.value === 0) {
    if (!changeForm.value.title || !changeForm.value.reason || !changeForm.value.effectiveDate) return false
    if (props.changeType === 'position_change') {
      return !!(positionChangeFields.value.newDepartmentName || positionChangeFields.value.newPositionName)
    }
    if (props.changeType === 'term_change') {
      return !!termChangeFields.value.newEndDate || !!termChangeFields.value.newTermType
    }
    return !!supplementaryContent.value
  }
  return true
})

/* ===== 下一步 ===== */
function handleNext() {
  if (currentStep.value === 0) {
    const details = buildChangeDetails()
    if (details.length === 0) {
      ElMessage.warning('请至少填写一项变更内容')
      return
    }
  }
  currentStep.value++
}

/* ===== 提交创建 ===== */
async function handleSubmit() {
  if (!props.contract) return
  submitLoading.value = true
  try {
    const details = buildChangeDetails()
    await contractApi.createChange({
      contractId: props.contract.id,
      changeType: props.changeType,
      title: changeForm.value.title,
      reason: changeForm.value.reason,
      changeDetails: details,
      effectiveDate: changeForm.value.effectiveDate,
      autoGenerateDocument: changeForm.value.autoGenerateDocument,
    })
    ElMessage.success('变更记录已创建')
    emit('success')
    handleClose()
  } catch (error: unknown) {
    if (error instanceof Error) ElMessage.error(error.message || '创建失败')
  } finally {
    submitLoading.value = false
  }
}

/* ===== 重置与关闭 ===== */
function resetForm() {
  currentStep.value = 0
  changeForm.value = { title: '', reason: '', effectiveDate: '', autoGenerateDocument: true }
  positionChangeFields.value = { newDepartmentName: '', newPositionName: '', newWorkLocation: '' }
  termChangeFields.value = { newEndDate: '', newTermType: '' }
  supplementaryContent.value = ''
}

function handleClose() {
  resetForm()
  emit('update:visible', false)
}

watch(() => props.visible, (val) => {
  if (!val) resetForm()
})
</script>

<template>
  <el-dialog
    :model-value="visible"
    title="合同变更"
    width="960px"
    class="fts-dialog--lg"
    destroy-on-close
    lock-scroll="false"
    :close-on-click-modal="false"
    @close="handleClose"
  >
    <!-- 变更类型标识 -->
    <div v-if="contract" style="margin-bottom: var(--fts-space-4);">
      <el-descriptions :column="2" border size="small">
        <el-descriptions-item label="员工姓名">{{ contract.employeeName }}</el-descriptions-item>
        <el-descriptions-item label="合同编号">{{ contract.contractNo }}</el-descriptions-item>
        <el-descriptions-item label="变更类型">
          <StatusTag :status="ContractChangeTypeTagMap[changeType]" :label="changeTypeLabel" size="small" />
        </el-descriptions-item>
        <el-descriptions-item label="合同状态">
          <StatusTag status="active" :label="'执行中'" size="small" />
        </el-descriptions-item>
      </el-descriptions>
    </div>

    <!-- 步骤条 -->
    <el-steps :active="currentStep" finish-status="success" align-center style="margin-bottom: var(--fts-space-4);">
      <el-step v-for="step in steps" :key="step.title" :title="step.title" :description="step.description" />
    </el-steps>

    <!-- 步骤1：填写变更信息 -->
    <div v-if="currentStep === 0">
      <el-form label-width="110px" style="max-width: 600px; margin: 0 auto;">
        <el-form-item label="变更标题" required>
          <el-input v-model="changeForm.title" placeholder="如：岗位变更协议" />
        </el-form-item>
        <el-form-item label="变更原因" required>
          <el-input v-model="changeForm.reason" type="textarea" :rows="2" placeholder="请说明变更原因" />
        </el-form-item>
        <el-form-item label="生效日期" required>
          <el-date-picker v-model="changeForm.effectiveDate" type="date" placeholder="选择生效日期" :teleported="false" value-format="YYYY-MM-DD" style="width: 100%;" />
        </el-form-item>

        <!-- 岗位/部门变更字段 -->
        <template v-if="changeType === 'position_change'">
          <el-divider content-position="left">变更内容</el-divider>
          <el-form-item label="新部门">
            <el-input v-model="positionChangeFields.newDepartmentName" placeholder="输入新部门名称" />
          </el-form-item>
          <el-form-item label="新职位">
            <el-input v-model="positionChangeFields.newPositionName" placeholder="输入新职位名称" />
          </el-form-item>
          <el-form-item label="新工作地点">
            <el-input v-model="positionChangeFields.newWorkLocation" placeholder="输入新工作地点" />
          </el-form-item>
        </template>

        <!-- 期限变更字段 -->
        <template v-if="changeType === 'term_change'">
          <el-divider content-position="left">变更内容</el-divider>
          <el-form-item label="新到期日期">
            <el-date-picker v-model="termChangeFields.newEndDate" type="date" placeholder="选择新到期日期" :teleported="false" value-format="YYYY-MM-DD" style="width: 100%;" />
          </el-form-item>
          <el-form-item label="新期限类型">
            <el-select v-model="termChangeFields.newTermType" placeholder="选择期限类型" :teleported="false" clearable style="width: 100%;">
              <el-option label="固定期限" value="fixed" />
              <el-option label="无固定期限" value="unfixed" />
              <el-option label="以完成一定工作任务为期限" value="task" />
            </el-select>
          </el-form-item>
        </template>

        <!-- 补充协议字段 -->
        <template v-if="changeType === 'supplementary'">
          <el-divider content-position="left">补充内容</el-divider>
          <el-form-item label="补充内容" required>
            <el-input v-model="supplementaryContent" type="textarea" :rows="4" placeholder="请输入补充协议的具体内容" />
          </el-form-item>
        </template>

        <el-form-item label="自动生成正文">
          <el-switch v-model="changeForm.autoGenerateDocument" />
          <span style="margin-left: var(--fts-space-2); color: var(--fts-text-secondary); font-size: 12px;">基于原合同模板自动生成补充协议正文</span>
        </el-form-item>
      </el-form>
    </div>

    <!-- 步骤2：变更对比 -->
    <div v-if="currentStep === 1">
      <ContentCard title="变更对比">
        <el-descriptions :column="1" border size="small">
          <el-descriptions-item v-for="detail in previewDetails" :key="detail.field" :label="detail.fieldLabel">
            <div style="display: flex; align-items: center; gap: var(--fts-space-3);">
              <span style="color: var(--fts-error); text-decoration: line-through;">{{ detail.beforeValue }}</span>
              <span style="color: var(--fts-text-secondary);">→</span>
              <span style="color: var(--fts-success); font-weight: 500;">{{ detail.afterValue }}</span>
            </div>
          </el-descriptions-item>
        </el-descriptions>
      </ContentCard>
      <ContentCard title="变更信息" style="margin-top: var(--fts-space-3);">
        <el-descriptions :column="2" border size="small">
          <el-descriptions-item label="变更标题">{{ changeForm.title }}</el-descriptions-item>
          <el-descriptions-item label="生效日期">{{ changeForm.effectiveDate }}</el-descriptions-item>
          <el-descriptions-item label="变更原因" :span="2">{{ changeForm.reason }}</el-descriptions-item>
          <el-descriptions-item label="自动生成正文">
            <StatusTag :status="changeForm.autoGenerateDocument ? 'active' : 'inactive'" :label="changeForm.autoGenerateDocument ? '是' : '否'" size="small" />
          </el-descriptions-item>
        </el-descriptions>
      </ContentCard>
    </div>

    <!-- 步骤3：提交确认 -->
    <div v-if="currentStep === 2">
      <el-alert type="warning" :closable="false" show-icon style="margin-bottom: var(--fts-space-3);">
        <template #title>变更确认</template>
        <div style="line-height: 1.6; margin-top: var(--fts-space-1);">
          提交后将创建变更记录，审批通过后变更生效并更新原合同信息。请确认变更内容无误。
        </div>
      </el-alert>
      <ContentCard title="变更摘要">
        <el-descriptions :column="2" border size="small">
          <el-descriptions-item label="员工">{{ contract?.employeeName }}</el-descriptions-item>
          <el-descriptions-item label="合同编号">{{ contract?.contractNo }}</el-descriptions-item>
          <el-descriptions-item label="变更类型">
            <StatusTag :status="ContractChangeTypeTagMap[changeType]" :label="changeTypeLabel" size="small" />
          </el-descriptions-item>
          <el-descriptions-item label="生效日期">{{ changeForm.effectiveDate }}</el-descriptions-item>
          <el-descriptions-item label="变更项数">{{ previewDetails.length }} 项</el-descriptions-item>
          <el-descriptions-item label="自动生成正文">
            <StatusTag :status="changeForm.autoGenerateDocument ? 'active' : 'inactive'" :label="changeForm.autoGenerateDocument ? '是' : '否'" size="small" />
          </el-descriptions-item>
        </el-descriptions>
      </ContentCard>
    </div>

    <template #footer>
      <div class="dialog-footer">
        <el-button v-if="currentStep > 0" @click="currentStep--">上一步</el-button>
        <el-button v-if="currentStep < 2" type="primary" :disabled="!canNext" @click="handleNext">下一步</el-button>
        <el-button v-if="currentStep === 2" type="primary" :loading="submitLoading" @click="handleSubmit">确认提交</el-button>
        <el-button @click="handleClose">取消</el-button>
      </div>
    </template>
  </el-dialog>
</template>
