export interface PermissionNode {
  id: string;
  name: string;
  icon?: string;
  children?: PermissionNode[];
  category?: string;
}

export interface ModulePermission {
  id: string;
  name: string;
  icon: string;
  category: string;
  permissions: string[];
}

/**
 * 系统模块权限注册表
 *
 * 设计原则：
 * 1. 权限码格式统一为 `{module}:{feature}:{action}`，如 `purchase:order:approve`
 * 2. 每个业务功能至少提供 `view` 权限，敏感操作补充 `create/edit/delete/approve/export`
 * 3. 保留 `{module}:manage` 和 `{module}:view` 作为兼容旧逻辑的通配权限
 * 4. 本文件为常量注册表，逻辑原子性较强，行数超过 TS 预警线属于合理范围
 */
export const systemModules: ModulePermission[] = [
  {
    id: "workspace",
    name: "工作台",
    icon: "odometer",
    category: "workspace",
    permissions: [
      "workspace:view",
      "workspace:dashboard:view",
      "workspace:todo:view",
      "workspace:todo:manage",
      "workspace:notification:view",
    ],
  },
  {
    id: "product",
    name: "产品中心",
    icon: "goods",
    category: "product",
    permissions: [
      "product:manage",
      "product:view",
      "product:food:view",
      "product:food:create",
      "product:food:edit",
      "product:food:delete",
      "product:category:view",
      "product:category:create",
      "product:category:edit",
      "product:category:delete",
      "product:combo:view",
      "product:combo:create",
      "product:combo:edit",
      "product:combo:delete",
      "product:pricing:view",
      "product:pricing:edit",
      "product:cost-analysis:view",
    ],
  },
  {
    id: "order",
    name: "订单管理",
    icon: "operation",
    category: "order",
    permissions: [
      "order:manage",
      "order:view",
      "order:query:view",
      "order:query:export",
      "order:statistics:view",
      "order:refund:view",
      "order:refund:process",
      "order:reservation:view",
      "order:reservation:create",
      "order:reservation:edit",
      "order:reservation:delete",
      "order:process",
      "order:edit",
      "order:delete",
      "order:print",
    ],
  },
  {
    id: "operations",
    name: "运营中心",
    icon: "data-board",
    category: "operations",
    permissions: [
      "operations:manage",
      "operations:view",
      "operations:dashboard:view",
      "operations:store-archive:view",
      "operations:store-archive:create",
      "operations:store-archive:edit",
      "operations:live-monitor:view",
      "operations:decision-board:view",
      "operations:decision-board:export",
      "operations:strategy-workshop:view",
      "operations:strategy-workshop:edit",
      "operations:alert-command-center:view",
      "operations:alert-command-center:manage",
      "operations:reports:view",
      "operations:reports:export",
    ],
  },
  {
    id: "store-management",
    name: "门店管理",
    icon: "shop",
    category: "operation",
    permissions: [
      "store:manage",
      "store:view",
      "store:pending-tasks:view",
      "store:receiving:view",
      "store:receiving:create",
      "store:inventory:view",
      "store:material-request:view",
      "store:material-request:create",
      "store:daily-settlement:view",
      "store:daily-settlement:create",
      "store:certificate:view",
      "store:certificate:manage",
      "store:shift:view",
      "store:shift:manage",
      "store:recruitment:view",
      "store:table-usage:view",
      "store:queue-history:view",
    ],
  },
  {
    id: "purchase",
    name: "采购管理",
    icon: "shopping-cart",
    category: "purchase",
    permissions: [
      "purchase:manage",
      "purchase:view",
      "purchase:overview:view",
      "purchase:material-category:view",
      "purchase:material-category:create",
      "purchase:material-category:edit",
      "purchase:material-category:delete",
      "purchase:archive:view",
      "purchase:archive:create",
      "purchase:archive:edit",
      "purchase:archive:delete",
      "purchase:supplier:view",
      "purchase:supplier:create",
      "purchase:supplier:edit",
      "purchase:supplier:delete",
      "purchase:material-request:view",
      "purchase:material-request:create",
      "purchase:material-request:edit",
      "purchase:material-request:delete",
      "purchase:request:view",
      "purchase:request:create",
      "purchase:request:edit",
      "purchase:request:delete",
      "purchase:request:submit",
      "purchase:request:approve",
      "purchase:plan:view",
      "purchase:plan:create",
      "purchase:plan:edit",
      "purchase:plan:delete",
      "purchase:plan:submit",
      "purchase:plan:approve",
      "purchase:plan:execute",
      "purchase:plan:export",
      "purchase:order:view",
      "purchase:order:create",
      "purchase:order:edit",
      "purchase:order:delete",
      "purchase:order:submit",
      "purchase:order:approve",
      "purchase:order:confirm",
      "purchase:order:cancel",
      "purchase:order:export",
      "purchase:stockin:view",
      "purchase:stockin:create",
      "purchase:stockin:edit",
      "purchase:stockin:delete",
      "purchase:stockin:confirm",
      "purchase:return:view",
      "purchase:return:create",
      "purchase:return:edit",
      "purchase:return:delete",
      "purchase:contract:view",
      "purchase:contract:create",
      "purchase:contract:edit",
      "purchase:contract:delete",
      "purchase:contract:sign",
      "purchase:electronic-contract:view",
      "purchase:electronic-contract:sign",
      "purchase:settlement:view",
      "purchase:settlement:create",
      "purchase:settlement:edit",
      "purchase:settlement:delete",
      "purchase:settlement:approve",
      "purchase:report:view",
      "purchase:report:export",
      "purchase:analysis:view",
    ],
  },
  {
    id: "warehouse",
    name: "仓储管理",
    icon: "box",
    category: "inventory",
    permissions: [
      "warehouse:manage",
      "warehouse:view",
      "warehouse:overview:view",
      "warehouse:inventory:view",
      "warehouse:inventory:create",
      "warehouse:inventory:edit",
      "warehouse:inventory:delete",
      "warehouse:stockin:view",
      "warehouse:stockin:create",
      "warehouse:stockin:edit",
      "warehouse:stockin:delete",
      "warehouse:outbound:view",
      "warehouse:outbound:create",
      "warehouse:outbound:edit",
      "warehouse:outbound:delete",
      "warehouse:outbound:approve",
      "warehouse:transfer:view",
      "warehouse:transfer:create",
      "warehouse:transfer:edit",
      "warehouse:transfer:delete",
      "warehouse:transfer:approve",
      "warehouse:adjust:view",
      "warehouse:adjust:create",
      "warehouse:adjust:edit",
      "warehouse:adjust:delete",
      "warehouse:loss:view",
      "warehouse:loss:create",
      "warehouse:loss:edit",
      "warehouse:loss:delete",
      "warehouse:check:view",
      "warehouse:check:create",
      "warehouse:check:edit",
      "warehouse:check:delete",
      "warehouse:warning:view",
      "warehouse:warning:manage",
      "warehouse:location:view",
      "warehouse:location:manage",
      "warehouse:store-inventory:view",
      "warehouse:report:view",
      "warehouse:report:export",
      "warehouse:smart-restock:view",
      "warehouse:detail:view",
      "warehouse:consumption:manage",
      "warehouse:log:view",
      "warehouse:settings:manage",
      "warehouse:store:manage",
    ],
  },
  {
    id: "member",
    name: "会员管理",
    icon: "user-filled",
    category: "marketing",
    permissions: [
      "member:manage",
      "member:view",
      "member:overview:view",
      "member:list:view",
      "member:list:create",
      "member:list:edit",
      "member:list:delete",
      "member:level:view",
      "member:level:manage",
      "member:recharge:view",
      "member:recharge:create",
      "member:recharge:refund",
      "member:recharge-settings:view",
      "member:recharge-settings:edit",
      "marketing:manage",
      "marketing:view",
      "marketing:member:manage",
      "marketing:promotion:manage",
    ],
  },
  {
    id: "finance",
    name: "财务管理",
    icon: "money",
    category: "finance",
    permissions: [
      "finance:manage",
      "finance:view",
      "finance:ledger:view",
      "finance:ledger:edit",
      "finance:subject:view",
      "finance:subject:manage",
      "finance:period:view",
      "finance:period:manage",
      "finance:receivable:view",
      "finance:receivable:manage",
      "finance:payable:view",
      "finance:payable:manage",
      "finance:cost:view",
      "finance:cost:manage",
      "finance:tax:view",
      "finance:tax:manage",
      "finance:invoice-reimbursement:view",
      "finance:invoice-reimbursement:manage",
      "finance:report:view",
      "finance:report:export",
      "finance:budget:view",
      "finance:budget:manage",
      "finance:fund:view",
      "finance:fund:manage",
      "finance:approval:view",
      "finance:approval:approve",
      "finance:auto-voucher:view",
      "finance:auto-voucher:manage",
      "finance:income:manage",
      "finance:expense:manage",
      "finance:profit:view",
      "finance:warning:manage",
      "finance:forecast:view",
    ],
  },
  {
    id: "asset",
    name: "资产管理",
    icon: "coin",
    category: "finance",
    permissions: [
      "asset:manage",
      "asset:view",
      "asset:overview:view",
      "asset:ledger:view",
      "asset:ledger:create",
      "asset:ledger:edit",
      "asset:ledger:delete",
      "asset:category:view",
      "asset:category:manage",
      "asset:depreciation:view",
      "asset:depreciation:manage",
      "asset:inventory-check:view",
      "asset:inventory-check:manage",
      "asset:maintenance:view",
      "asset:maintenance:manage",
      "asset:disposal:view",
      "asset:disposal:manage",
      "asset:report:view",
    ],
  },
  {
    id: "hr",
    name: "人事管理",
    icon: "users",
    category: "hr",
    permissions: [
      "hr:manage",
      "hr:view",
      "hr:employee:view",
      "hr:employee:create",
      "hr:employee:edit",
      "hr:employee:delete",
      "hr:organization:view",
      "hr:organization:manage",
      "hr:position:view",
      "hr:position:manage",
      "hr:attendance:view",
      "hr:attendance:manage",
      "hr:recruitment:view",
      "hr:recruitment:manage",
      "hr:onboarding:view",
      "hr:onboarding:manage",
      "hr:training:view",
      "hr:training:manage",
      "hr:study-record:view",
      "hr:study-record:manage",
      "hr:health-certificate:view",
      "hr:health-certificate:manage",
      "hr:contract:view",
      "hr:contract:create",
      "hr:contract:edit",
      "hr:contract:delete",
      "hr:contract-template:view",
      "hr:contract-template:manage",
      "hr:contract-template-library:view",
      "hr:contract-template-library:manage",
      "hr:salary:view",
      "hr:salary:manage",
      "hr:approval:view",
      "hr:approval:approve",
      "hr:knowledge-intelligence:view",
      "hr:analytics:view",
      "hr:analytics:export",
      "hr:employee-intelligence:view",
      "hr:invitation-code:view",
      "hr:invitation-code:manage",
      "hr:config-center:view",
      "hr:config-center:manage",
      "hr:employee:manage",
      "hr:organization:manage",
      "hr:attendance:manage",
      "hr:recruitment:manage",
      "hr:health:manage",
      "hr:contract:manage",
      "hr:probation:manage",
    ],
  },
  {
    id: "traceability",
    name: "食品追溯",
    icon: "location",
    category: "traceability",
    permissions: [
      "traceability:manage",
      "traceability:view",
      "traceability:query:view",
      "traceability:material-code:view",
      "traceability:food-trace-code:view",
      "traceability:food-trace-code:create",
      "traceability:chain:view",
      "traceability:supplier:view",
      "traceability:inspection:view",
      "traceability:inspection:create",
      "traceability:inspection:edit",
      "traceability:label-template:view",
      "traceability:label-template:manage",
      "traceability:recall:view",
      "traceability:recall:manage",
      "traceability:quality:view",
      "traceability:expiry-warning:view",
    ],
  },
  {
    id: "device",
    name: "设备管理",
    icon: "monitor",
    category: "system",
    permissions: [
      "device:manage",
      "device:view",
      "device:list:view",
      "device:list:manage",
      "device:monitor:view",
      "device:alerts:view",
      "device:alerts:manage",
      "device:status-history:view",
    ],
  },
  {
    id: "seal",
    name: "电子签章",
    icon: "stamp",
    category: "system",
    permissions: [
      "seal:manage",
      "seal:view",
      "seal:management:view",
      "seal:management:create",
      "seal:management:edit",
      "seal:management:delete",
      "seal:management:use",
      "seal:sign:view",
      "seal:sign:execute",
    ],
  },
  {
    id: "system",
    name: "系统设置",
    icon: "setting",
    category: "system",
    permissions: [
      "system:manage",
      "system:view",
      "system:user:view",
      "system:user:create",
      "system:user:edit",
      "system:user:delete",
      "system:role:view",
      "system:role:create",
      "system:role:edit",
      "system:role:delete",
      "system:menu:view",
      "system:menu:manage",
      "system:permission-center:view",
      "system:permission-center:manage",
      "system:operation-audit:view",
      "system:ai-model-config:view",
      "system:ai-model-config:manage",
      "system:company-init:manage",
      "user:manage",
      "role:manage",
      "menu:manage",
      "operation:log:view",
    ],
  },
];

export const permissionDescriptions: Record<string, string> = {
  "workspace:view": "查看工作台",
  "workspace:dashboard:view": "查看工作台首页",
  "workspace:todo:view": "查看待办事项",
  "workspace:todo:manage": "管理待办事项",
  "workspace:notification:view": "查看系统通知",

  "product:manage": "管理产品相关功能",
  "product:view": "查看产品信息",
  "product:food:view": "查看菜品",
  "product:food:create": "新增菜品",
  "product:food:edit": "编辑菜品",
  "product:food:delete": "删除菜品",
  "product:category:view": "查看菜品分类",
  "product:category:create": "新增菜品分类",
  "product:category:edit": "编辑菜品分类",
  "product:category:delete": "删除菜品分类",
  "product:combo:view": "查看套餐",
  "product:combo:create": "新增套餐",
  "product:combo:edit": "编辑套餐",
  "product:combo:delete": "删除套餐",
  "product:pricing:view": "查看菜品定价",
  "product:pricing:edit": "编辑菜品定价",
  "product:cost-analysis:view": "查看菜品成本分析",

  "order:manage": "管理订单相关功能",
  "order:view": "查看订单信息",
  "order:query:view": "查看订单查询",
  "order:query:export": "导出订单数据",
  "order:statistics:view": "查看订单统计",
  "order:refund:view": "查看退款管理",
  "order:refund:process": "处理退款",
  "order:reservation:view": "查看预约管理",
  "order:reservation:create": "新增预约",
  "order:reservation:edit": "编辑预约",
  "order:reservation:delete": "删除预约",
  "order:process": "处理订单",
  "order:edit": "编辑订单",
  "order:delete": "删除订单",
  "order:print": "打印订单",

  "operations:manage": "管理运营中心",
  "operations:view": "查看运营中心",
  "operations:dashboard:view": "查看运营总览",
  "operations:store-archive:view": "查看门店档案",
  "operations:store-archive:create": "新增门店档案",
  "operations:store-archive:edit": "编辑门店档案",
  "operations:live-monitor:view": "查看实时监控",
  "operations:decision-board:view": "查看经营分析",
  "operations:decision-board:export": "导出经营分析",
  "operations:strategy-workshop:view": "查看运营策略",
  "operations:strategy-workshop:edit": "编辑运营策略",
  "operations:alert-command-center:view": "查看预警管理",
  "operations:alert-command-center:manage": "管理预警规则",
  "operations:reports:view": "查看经营报表",
  "operations:reports:export": "导出经营报表",

  "store:manage": "管理门店相关功能",
  "store:view": "查看门店信息",
  "store:pending-tasks:view": "查看待办事项",
  "store:receiving:view": "查看门店收货",
  "store:receiving:create": "登记门店收货",
  "store:inventory:view": "查看门店库存",
  "store:material-request:view": "查看物资需求",
  "store:material-request:create": "提交物资需求",
  "store:daily-settlement:view": "查看日结对账",
  "store:daily-settlement:create": "执行日结对账",
  "store:certificate:view": "查看证件管理",
  "store:certificate:manage": "管理证件",
  "store:shift:view": "查看排班管理",
  "store:shift:manage": "管理排班",
  "store:recruitment:view": "查看门店招聘",
  "store:table-usage:view": "查看桌台记录",
  "store:queue-history:view": "查看叫号记录",

  "purchase:manage": "管理采购相关功能",
  "purchase:view": "查看采购信息",
  "purchase:overview:view": "查看采购概览",
  "purchase:material-category:view": "查看商品分类",
  "purchase:material-category:create": "新增商品分类",
  "purchase:material-category:edit": "编辑商品分类",
  "purchase:material-category:delete": "删除商品分类",
  "purchase:archive:view": "查看商品档案",
  "purchase:archive:create": "新增商品档案",
  "purchase:archive:edit": "编辑商品档案",
  "purchase:archive:delete": "删除商品档案",
  "purchase:supplier:view": "查看供应商档案",
  "purchase:supplier:create": "新增供应商档案",
  "purchase:supplier:edit": "编辑供应商档案",
  "purchase:supplier:delete": "删除供应商档案",
  "purchase:material-request:view": "查看物资需求提报",
  "purchase:material-request:create": "新增物资需求提报",
  "purchase:material-request:edit": "编辑物资需求提报",
  "purchase:material-request:delete": "删除物资需求提报",
  "purchase:request:view": "查看采购申请",
  "purchase:request:create": "新增采购申请",
  "purchase:request:edit": "编辑采购申请",
  "purchase:request:delete": "删除采购申请",
  "purchase:request:submit": "提交采购申请审批",
  "purchase:request:approve": "审批采购申请",
  "purchase:plan:view": "查看采购计划",
  "purchase:plan:create": "新增采购计划",
  "purchase:plan:edit": "编辑采购计划",
  "purchase:plan:delete": "删除采购计划",
  "purchase:plan:submit": "提交采购计划审批",
  "purchase:plan:approve": "审批采购计划",
  "purchase:plan:execute": "开始执行采购计划",
  "purchase:plan:export": "导出采购计划",
  "purchase:order:view": "查看采购订单",
  "purchase:order:create": "新增采购订单",
  "purchase:order:edit": "编辑采购订单",
  "purchase:order:delete": "删除采购订单",
  "purchase:order:submit": "提交采购订单审批",
  "purchase:order:approve": "审批采购订单",
  "purchase:order:confirm": "确认采购订单",
  "purchase:order:cancel": "终止采购订单",
  "purchase:order:export": "导出采购订单",
  "purchase:stockin:view": "查看到货登记",
  "purchase:stockin:create": "新增到货登记",
  "purchase:stockin:edit": "编辑到货登记",
  "purchase:stockin:delete": "删除到货登记",
  "purchase:stockin:confirm": "确认到货登记",
  "purchase:return:view": "查看采购退货",
  "purchase:return:create": "新增采购退货",
  "purchase:return:edit": "编辑采购退货",
  "purchase:return:delete": "删除采购退货",
  "purchase:contract:view": "查看采购合同",
  "purchase:contract:create": "新增采购合同",
  "purchase:contract:edit": "编辑采购合同",
  "purchase:contract:delete": "删除采购合同",
  "purchase:contract:sign": "签署采购合同",
  "purchase:electronic-contract:view": "查看电子合同",
  "purchase:electronic-contract:sign": "签署电子合同",
  "purchase:settlement:view": "查看采购结算",
  "purchase:settlement:create": "新增采购结算",
  "purchase:settlement:edit": "编辑采购结算",
  "purchase:settlement:delete": "删除采购结算",
  "purchase:settlement:approve": "审批采购结算",
  "purchase:report:view": "查看采购报表",
  "purchase:report:export": "导出采购报表",
  "purchase:analysis:view": "查看采购数据分析",

  "warehouse:manage": "管理仓储相关功能",
  "warehouse:view": "查看仓储信息",
  "warehouse:overview:view": "查看库存概览",
  "warehouse:inventory:view": "查看库存管理",
  "warehouse:inventory:create": "新增库存记录",
  "warehouse:inventory:edit": "编辑库存记录",
  "warehouse:inventory:delete": "删除库存记录",
  "warehouse:stockin:view": "查看库存入库",
  "warehouse:stockin:create": "新增库存入库",
  "warehouse:stockin:edit": "编辑库存入库",
  "warehouse:stockin:delete": "删除库存入库",
  "warehouse:outbound:view": "查看库存出库",
  "warehouse:outbound:create": "新增库存出库",
  "warehouse:outbound:edit": "编辑库存出库",
  "warehouse:outbound:delete": "删除库存出库",
  "warehouse:outbound:approve": "审批库存出库",
  "warehouse:transfer:view": "查看库存调拨",
  "warehouse:transfer:create": "新增库存调拨",
  "warehouse:transfer:edit": "编辑库存调拨",
  "warehouse:transfer:delete": "删除库存调拨",
  "warehouse:transfer:approve": "审批库存调拨",
  "warehouse:adjust:view": "查看库存调整",
  "warehouse:adjust:create": "新增库存调整",
  "warehouse:adjust:edit": "编辑库存调整",
  "warehouse:adjust:delete": "删除库存调整",
  "warehouse:loss:view": "查看库存报损",
  "warehouse:loss:create": "新增库存报损",
  "warehouse:loss:edit": "编辑库存报损",
  "warehouse:loss:delete": "删除库存报损",
  "warehouse:check:view": "查看库存盘点",
  "warehouse:check:create": "新增库存盘点",
  "warehouse:check:edit": "编辑库存盘点",
  "warehouse:check:delete": "删除库存盘点",
  "warehouse:warning:view": "查看库存预警",
  "warehouse:warning:manage": "管理库存预警",
  "warehouse:location:view": "查看库位管理",
  "warehouse:location:manage": "管理库位",
  "warehouse:store-inventory:view": "查看门店库存",
  "warehouse:report:view": "查看库存报表",
  "warehouse:report:export": "导出库存报表",
  "warehouse:smart-restock:view": "查看智能补货建议",
  "warehouse:detail:view": "查看库存明细",
  "warehouse:consumption:manage": "管理库存消耗",
  "warehouse:log:view": "查看库存日志",
  "warehouse:settings:manage": "管理仓库设置",
  "warehouse:store:manage": "管理门店库存",

  "member:manage": "管理会员相关功能",
  "member:view": "查看会员信息",
  "member:overview:view": "查看会员概览",
  "member:list:view": "查看会员列表",
  "member:list:create": "新增会员",
  "member:list:edit": "编辑会员",
  "member:list:delete": "删除会员",
  "member:level:view": "查看会员等级",
  "member:level:manage": "管理会员等级",
  "member:recharge:view": "查看储值管理",
  "member:recharge:create": "新增储值",
  "member:recharge:refund": "储值退款",
  "member:recharge-settings:view": "查看储值系统设置",
  "member:recharge-settings:edit": "编辑储值系统设置",
  "marketing:manage": "管理营销相关功能",
  "marketing:view": "查看营销信息",
  "marketing:member:manage": "管理会员营销",
  "marketing:promotion:manage": "管理营销活动",

  "finance:manage": "管理财务相关功能",
  "finance:view": "查看财务信息",
  "finance:ledger:view": "查看财务总账",
  "finance:ledger:edit": "编辑财务总账",
  "finance:subject:view": "查看会计科目",
  "finance:subject:manage": "管理会计科目",
  "finance:period:view": "查看会计期间",
  "finance:period:manage": "管理会计期间",
  "finance:receivable:view": "查看应收账款",
  "finance:receivable:manage": "管理应收账款",
  "finance:payable:view": "查看应付账款",
  "finance:payable:manage": "管理应付账款",
  "finance:cost:view": "查看成本管理",
  "finance:cost:manage": "管理成本",
  "finance:tax:view": "查看税务管理",
  "finance:tax:manage": "管理税务",
  "finance:invoice-reimbursement:view": "查看发票报销",
  "finance:invoice-reimbursement:manage": "管理发票报销",
  "finance:report:view": "查看财务报表",
  "finance:report:export": "导出财务报表",
  "finance:budget:view": "查看预算管理",
  "finance:budget:manage": "管理预算",
  "finance:fund:view": "查看资金管理",
  "finance:fund:manage": "管理资金",
  "finance:approval:view": "查看财务审批",
  "finance:approval:approve": "审批财务单据",
  "finance:auto-voucher:view": "查看自动凭证管理",
  "finance:auto-voucher:manage": "管理自动凭证",
  "finance:income:manage": "管理收入",
  "finance:expense:manage": "管理支出",
  "finance:profit:view": "查看利润分析",
  "finance:warning:manage": "管理财务预警",
  "finance:forecast:view": "查看财务预测",

  "asset:manage": "管理资产相关功能",
  "asset:view": "查看资产信息",
  "asset:overview:view": "查看资产概览",
  "asset:ledger:view": "查看资产台账",
  "asset:ledger:create": "新增资产台账",
  "asset:ledger:edit": "编辑资产台账",
  "asset:ledger:delete": "删除资产台账",
  "asset:category:view": "查看资产分类",
  "asset:category:manage": "管理资产分类",
  "asset:depreciation:view": "查看资产折旧",
  "asset:depreciation:manage": "管理资产折旧",
  "asset:inventory-check:view": "查看资产盘点",
  "asset:inventory-check:manage": "管理资产盘点",
  "asset:maintenance:view": "查看资产维护",
  "asset:maintenance:manage": "管理资产维护",
  "asset:disposal:view": "查看资产处置",
  "asset:disposal:manage": "管理资产处置",
  "asset:report:view": "查看资产报表",

  "hr:manage": "管理人事相关功能",
  "hr:view": "查看人事信息",
  "hr:employee:view": "查看员工",
  "hr:employee:create": "新增员工",
  "hr:employee:edit": "编辑员工",
  "hr:employee:delete": "删除员工",
  "hr:organization:view": "查看组织架构",
  "hr:organization:manage": "管理组织架构",
  "hr:position:view": "查看岗位",
  "hr:position:manage": "管理岗位",
  "hr:attendance:view": "查看考勤排班",
  "hr:attendance:manage": "管理考勤排班",
  "hr:recruitment:view": "查看招聘管理",
  "hr:recruitment:manage": "管理招聘",
  "hr:onboarding:view": "查看入职办理",
  "hr:onboarding:manage": "办理入职",
  "hr:training:view": "查看培训发展",
  "hr:training:manage": "管理培训",
  "hr:study-record:view": "查看学习记录",
  "hr:study-record:manage": "管理学习记录",
  "hr:health-certificate:view": "查看健康证管理",
  "hr:health-certificate:manage": "管理健康证",
  "hr:contract:view": "查看合同",
  "hr:contract:create": "新增合同",
  "hr:contract:edit": "编辑合同",
  "hr:contract:delete": "删除合同",
  "hr:contract-template:view": "查看合同模板",
  "hr:contract-template:manage": "管理合同模板",
  "hr:contract-template-library:view": "查看合同模板库",
  "hr:contract-template-library:manage": "管理合同模板库",
  "hr:salary:view": "查看薪资管理",
  "hr:salary:manage": "管理薪资",
  "hr:approval:view": "查看合规审批",
  "hr:approval:approve": "审批合规单据",
  "hr:knowledge-intelligence:view": "查看知识库智能",
  "hr:analytics:view": "查看人事分析",
  "hr:analytics:export": "导出人事分析",
  "hr:employee-intelligence:view": "查看员工画像",
  "hr:invitation-code:view": "查看邀请码管理",
  "hr:invitation-code:manage": "管理邀请码",
  "hr:config-center:view": "查看配置中心",
  "hr:config-center:manage": "管理人事配置",
  "hr:employee:manage": "管理员工",
  "hr:organization:manage": "管理组织架构",
  "hr:attendance:manage": "管理考勤",
  "hr:recruitment:manage": "管理招聘",
  "hr:health:manage": "管理健康",
  "hr:contract:manage": "管理合同",
  "hr:probation:manage": "管理试用",

  "traceability:manage": "管理食品追溯",
  "traceability:view": "查看食品追溯",
  "traceability:query:view": "查看追溯查询",
  "traceability:material-code:view": "查看原料追溯",
  "traceability:food-trace-code:view": "查看食品追溯码",
  "traceability:food-trace-code:create": "生成食品追溯码",
  "traceability:chain:view": "查看追溯链展示",
  "traceability:supplier:view": "查看供应商追溯",
  "traceability:inspection:view": "查看检验记录",
  "traceability:inspection:create": "新增检验记录",
  "traceability:inspection:edit": "编辑检验记录",
  "traceability:label-template:view": "查看标签模板",
  "traceability:label-template:manage": "管理标签模板",
  "traceability:recall:view": "查看召回管理",
  "traceability:recall:manage": "管理召回",
  "traceability:quality:view": "查看质量追溯",
  "traceability:expiry-warning:view": "查看临期预警",

  "device:manage": "管理设备相关功能",
  "device:view": "查看设备信息",
  "device:list:view": "查看设备列表",
  "device:list:manage": "管理设备列表",
  "device:monitor:view": "查看设备监控",
  "device:alerts:view": "查看设备告警",
  "device:alerts:manage": "管理设备告警",
  "device:status-history:view": "查看状态历史",

  "seal:manage": "管理电子签章",
  "seal:view": "查看电子签章",
  "seal:management:view": "查看印章管理",
  "seal:management:create": "新增印章",
  "seal:management:edit": "编辑印章",
  "seal:management:delete": "删除印章",
  "seal:management:use": "使用印章",
  "seal:sign:view": "查看签署任务",
  "seal:sign:execute": "执行签署",

  "system:manage": "管理系统设置",
  "system:view": "查看系统信息",
  "system:user:view": "查看用户",
  "system:user:create": "新增用户",
  "system:user:edit": "编辑用户",
  "system:user:delete": "删除用户",
  "system:role:view": "查看角色",
  "system:role:create": "新增角色",
  "system:role:edit": "编辑角色",
  "system:role:delete": "删除角色",
  "system:menu:view": "查看菜单",
  "system:menu:manage": "管理菜单",
  "system:permission-center:view": "查看权限中心",
  "system:permission-center:manage": "管理权限中心",
  "system:operation-audit:view": "查看操作审计",
  "system:ai-model-config:view": "查看AI模型配置",
  "system:ai-model-config:manage": "管理AI模型配置",
  "system:company-init:manage": "执行公司初始化",
  "user:manage": "管理用户",
  "role:manage": "管理角色",
  "menu:manage": "管理菜单",
  "operation:log:view": "查看操作日志",
};

export function generatePermissionTree(): PermissionNode[] {
  return systemModules.map((module) => ({
    id: module.id,
    name: module.name,
    icon: module.icon,
    category: module.category,
    children: module.permissions.map((perm) => ({
      id: perm,
      name: permissionDescriptions[perm] || perm,
    })),
  }));
}

export function getPermissionDescription(permission: string): string {
  return permissionDescriptions[permission] || permission;
}

export function getModulePermissions(moduleId: string): string[] {
  const module = systemModules.find((m) => m.id === moduleId);
  return module?.permissions || [];
}

export function getAllPermissions(): string[] {
  return systemModules.flatMap((module) => module.permissions);
}
