-- ============================================================
-- [DEPRECATED] 本文件为参考性 SQL，不再被项目使用
-- 项目实际使用 *DatabaseInitializer 模式（Java 代码建表）
-- 活跃迁移脚本位于 db/migration/V*.sql（Flyway 管理）
-- H2 环境使用 db/schema.sql + db/data.sql（spring.sql.init）
-- 财务模块使用 db/finance_tables.sql（FinanceDatabaseInitializer）
-- 请勿作为数据库初始化脚本引用
-- 标注时间：2026-06-30
-- ============================================================
-- 创建订单表
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID VARCHAR(32) PRIMARY KEY,
    USER_ID VARCHAR(32),
    ORDER_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    ORDER_TYPE TINYINT DEFAULT 0,
    ORDER_STATUS TINYINT DEFAULT 0,
    ORDER_AMOUNT DECIMAL(10,2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10,2) DEFAULT 0.00,
    ACTUAL_AMOUNT DECIMAL(10,2) NOT NULL,
    PAYMENT_METHOD TINYINT,
    PAYMENT_TIME DATETIME,
    DELIVERY_ADDRESS VARCHAR(255),
    CONTACT_NAME VARCHAR(50),
    CONTACT_PHONE VARCHAR(20),
    REMARKS TEXT,
    ORDER_SOURCE TINYINT DEFAULT 0,
    MERCHANT_ID VARCHAR(32),
    DELIVERYMAN_ID VARCHAR(32),
    ESTIMATED_DELIVERY_TIME DATETIME,
    ACTUAL_DELIVERY_TIME DATETIME,
    CANCEL_REASON VARCHAR(255),
    REFUND_REASON VARCHAR(255),
    REFUND_AMOUNT DECIMAL(10,2) DEFAULT 0.00,
    REFUND_TIME DATETIME,
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50),
    DELETED TINYINT DEFAULT 0
);

-- 创建订单表索引
CREATE INDEX IDX_ORDERS_USER_ID ON ORDERS(USER_ID);
CREATE INDEX IDX_ORDERS_ORDER_NUMBER ON ORDERS(ORDER_NUMBER);
CREATE INDEX IDX_ORDERS_ORDER_STATUS ON ORDERS(ORDER_STATUS);
CREATE INDEX IDX_ORDERS_CREATE_TIME ON ORDERS(CREATE_TIME);
CREATE INDEX IDX_ORDERS_DELETED ON ORDERS(DELETED);

-- 创建订单项表
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_ID VARCHAR(32) PRIMARY KEY,
    ORDER_ID VARCHAR(32) NOT NULL,
    FOOD_ID VARCHAR(32) NOT NULL,
    FOOD_NAME VARCHAR(100) NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    QUANTITY INT NOT NULL,
    SUBTOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    FOOD_IMAGE_URL VARCHAR(255),
    SPECIFICATION VARCHAR(100),
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE
);

-- 创建订单项表索引
CREATE INDEX IDX_ORDER_ITEMS_ORDER_ID ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_FOOD_ID ON ORDER_ITEMS(FOOD_ID);
CREATE INDEX IDX_ORDER_ITEMS_DELETED ON ORDER_ITEMS(DELETED);
