-- Food Traceability System Database Initialization Script
-- H2 database doesn't support CREATE DATABASE and USE statements, database name is specified during connection

-- User table
-- 注意：STATUS 字段使用 VARCHAR(20) 以与生产 PostgreSQL schema (V1.0.0.100) 保持一致。
-- User 实体中 status 为 String 类型，H2 中如使用 SMALLINT 会导致 "active" 等字符串值无法存储。
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    PHONE VARCHAR(20),
    NAME VARCHAR(100),
    AVATAR VARCHAR(255),
    STATUS VARCHAR(20) DEFAULT '1',
    DEPARTMENT_ID BIGINT,
    STORE_ID BIGINT,
    EMPLOYEE_CODE VARCHAR(50) DEFAULT NULL,
    ROLES TEXT,
    ROLE_NAMES VARCHAR(255),
    LAST_LOGIN_TIME TIMESTAMP,
    LAST_LOGIN_IP VARCHAR(50),
    IS_LOCKED SMALLINT DEFAULT 0,
    LOCK_TIME TIMESTAMP,
    PASSWORD_ERROR_COUNT INT DEFAULT 0,
    LAST_PASSWORD_ERROR_TIME TIMESTAMP,
    NEED_CHANGE_PASSWORD SMALLINT DEFAULT 0,
    LAST_PASSWORD_CHANGE_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT
);

-- Create indexes
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_STATUS ON USERS(STATUS);
CREATE INDEX IDX_USERS_DEPARTMENT ON USERS(DEPARTMENT_ID);
CREATE INDEX IDX_USERS_DELETED ON USERS(DELETED);

-- Role table
-- 注意：STATUS 字段使用 VARCHAR(20) 以与生产 PostgreSQL schema (V1.0.0.100) 保持一致。
-- UserMapper.getUserRoles() 查询使用 r.STATUS IN ('1', 'active')，需要字符串类型。
CREATE TABLE IF NOT EXISTS ROLES (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_CODE VARCHAR(50) NOT NULL UNIQUE,
    ROLE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    ROLE_TYPE SMALLINT DEFAULT 1,
    LEVEL INT DEFAULT 1,
    STATUS VARCHAR(20) DEFAULT '1',
    IS_SYSTEM SMALLINT DEFAULT 0,
    PARENT_ID BIGINT DEFAULT 0,
    DATA_SCOPE VARCHAR(50) DEFAULT 'all',
    ACCESSIBLE_STORES TEXT,
    ACCESSIBLE_DEPARTMENTS TEXT,
    PERMISSIONS TEXT,
    VERSION INT DEFAULT 1,
    EXT_DATA TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT
);

-- Create indexes
CREATE INDEX IDX_ROLES_ROLE_CODE ON ROLES(ROLE_CODE);
CREATE INDEX IDX_ROLES_STATUS ON ROLES(STATUS);
CREATE INDEX IDX_ROLES_DELETED ON ROLES(DELETED);

-- Permission table
-- 注意：STATUS 字段使用 VARCHAR(20) 以与生产 PostgreSQL schema 保持一致。
-- UserMapper.xml 中 getUserPermissions/getUserRolePermissions 查询使用 p.STATUS IN ('1', 'active')，需要字符串类型。
CREATE TABLE IF NOT EXISTS PERMISSIONS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PERMISSION_CODE VARCHAR(100) NOT NULL UNIQUE,
    PERMISSION_NAME VARCHAR(100) NOT NULL,
    PERMISSION_TYPE SMALLINT DEFAULT 1,
    MODULE VARCHAR(50),
    PARENT_ID BIGINT DEFAULT 0,
    LEVEL INT DEFAULT 1,
    SORT_ORDER INT DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT '1',
    ICON VARCHAR(100),
    PATH VARCHAR(200),
    COMPONENT VARCHAR(100),
    REDIRECT VARCHAR(200),
    IS_HIDDEN SMALLINT DEFAULT 0,
    IS_CACHE SMALLINT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT
);

-- Create indexes
CREATE INDEX IDX_PERMISSIONS_PERMISSION_CODE ON PERMISSIONS(PERMISSION_CODE);
CREATE INDEX IDX_PERMISSIONS_PARENT_ID ON PERMISSIONS(PARENT_ID);
CREATE INDEX IDX_PERMISSIONS_STATUS ON PERMISSIONS(STATUS);
CREATE INDEX IDX_PERMISSIONS_DELETED ON PERMISSIONS(DELETED);

-- User role relationship table
CREATE TABLE IF NOT EXISTS USER_ROLES (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    CREATED_BY BIGINT,
    UNIQUE (USER_ID, ROLE_ID)
);

-- Create indexes
CREATE INDEX IDX_USER_ROLES_USER_ID ON USER_ROLES(USER_ID);
CREATE INDEX IDX_USER_ROLES_ROLE_ID ON USER_ROLES(ROLE_ID);
CREATE INDEX IDX_USER_ROLES_DELETED ON USER_ROLES(DELETED);

-- Role permission relationship table
CREATE TABLE IF NOT EXISTS ROLE_PERMISSIONS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    CREATED_BY BIGINT,
    UNIQUE (ROLE_ID, PERMISSION_ID)
);

-- Create indexes
CREATE INDEX IDX_ROLE_PERMISSIONS_ROLE_ID ON ROLE_PERMISSIONS(ROLE_ID);
CREATE INDEX IDX_ROLE_PERMISSIONS_PERMISSION_ID ON ROLE_PERMISSIONS(PERMISSION_ID);
CREATE INDEX IDX_ROLE_PERMISSIONS_DELETED ON ROLE_PERMISSIONS(DELETED);

-- User permission relationship table (direct permissions)
CREATE TABLE IF NOT EXISTS USER_PERMISSIONS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    CREATED_BY BIGINT,
    UNIQUE (USER_ID, PERMISSION_ID)
);

-- Create indexes
CREATE INDEX IDX_USER_PERMISSIONS_USER_ID ON USER_PERMISSIONS(USER_ID);
CREATE INDEX IDX_USER_PERMISSIONS_PERMISSION_ID ON USER_PERMISSIONS(PERMISSION_ID);
CREATE INDEX IDX_USER_PERMISSIONS_DELETED ON USER_PERMISSIONS(DELETED);

-- Department table
CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPT_CODE VARCHAR(50) NOT NULL UNIQUE,
    DEPT_NAME VARCHAR(100) NOT NULL,
    PARENT_ID BIGINT DEFAULT 0,
    LEVEL INT DEFAULT 1,
    SORT_ORDER INT DEFAULT 0,
    STATUS SMALLINT DEFAULT 1,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT
);

-- Create indexes
CREATE INDEX IDX_DEPARTMENTS_DEPT_CODE ON DEPARTMENTS(DEPT_CODE);
CREATE INDEX IDX_DEPARTMENTS_PARENT_ID ON DEPARTMENTS(PARENT_ID);
CREATE INDEX IDX_DEPARTMENTS_STATUS ON DEPARTMENTS(STATUS);
CREATE INDEX IDX_DEPARTMENTS_DELETED ON DEPARTMENTS(DELETED);

-- Promotion table (create table first)
CREATE TABLE IF NOT EXISTS PROMOTIONS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    TYPE SMALLINT NOT NULL DEFAULT 1,
    DISCOUNT_TYPE SMALLINT,
    DISCOUNT_VALUE DECIMAL(10,2),
    MIN_AMOUNT DECIMAL(10,2),
    MAX_DISCOUNT DECIMAL(10,2),
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    STATUS SMALLINT DEFAULT 1,
    IS_FEATURED SMALLINT DEFAULT 0,
    SORT_ORDER INT DEFAULT 0,
    PARTICIPATION_LIMIT INT DEFAULT 0,
    PARTICIPATION_COUNT INT DEFAULT 0,
    IMAGE_URL VARCHAR(500),
    BANNER_URL VARCHAR(500),
    APPLICABLE_PRODUCTS TEXT,
    APPLICABLE_CATEGORIES TEXT,
    RULES TEXT,
    TERMS_CONDITIONS TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT
);

-- Create promotion table indexes
CREATE INDEX IDX_PROMOTIONS_TYPE ON PROMOTIONS(TYPE);
CREATE INDEX IDX_PROMOTIONS_STATUS ON PROMOTIONS(STATUS);
CREATE INDEX IDX_PROMOTIONS_START_TIME ON PROMOTIONS(START_TIME);
CREATE INDEX IDX_PROMOTIONS_END_TIME ON PROMOTIONS(END_TIME);
CREATE INDEX IDX_PROMOTIONS_IS_FEATURED ON PROMOTIONS(IS_FEATURED);
CREATE INDEX IDX_PROMOTIONS_DELETED ON PROMOTIONS(DELETED);

-- Finance record table
CREATE TABLE IF NOT EXISTS FINANCE_RECORD (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    CATEGORY VARCHAR(100),
    BUSINESS_ID BIGINT,
    BUSINESS_TYPE VARCHAR(50),
    DESCRIPTION TEXT,
    RECORD_DATE TIMESTAMP NOT NULL,
    CREATE_BY VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0
);

-- Create finance record table indexes
CREATE INDEX IDX_FINANCE_RECORD_TYPE ON FINANCE_RECORD(TYPE);
CREATE INDEX IDX_FINANCE_RECORD_STATUS ON FINANCE_RECORD(STATUS);
CREATE INDEX IDX_FINANCE_RECORD_RECORD_DATE ON FINANCE_RECORD(RECORD_DATE);
CREATE INDEX IDX_FINANCE_RECORD_DELETED ON FINANCE_RECORD(DELETED);

-- Finance statistics table
CREATE TABLE IF NOT EXISTS FINANCE_STATISTICS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STATISTICS_DATE DATE NOT NULL,
    INCOME_AMOUNT DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    EXPENSE_AMOUNT DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    PROFIT_AMOUNT DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (STATISTICS_DATE)
);

-- Create finance statistics table indexes
CREATE INDEX IDX_FINANCE_STATISTICS_DATE ON FINANCE_STATISTICS(STATISTICS_DATE);

-- Product table
CREATE TABLE IF NOT EXISTS product (
    product_id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    code          VARCHAR(50),
    category_id   BIGINT,
    category_name VARCHAR(100),
    unit          VARCHAR(20),
    price         DECIMAL(12,2),
    cost_price    DECIMAL(12,2),
    barcode       VARCHAR(100),
    specification VARCHAR(200),
    origin        VARCHAR(200),
    supplier_id   BIGINT,
    supplier_name VARCHAR(200),
    status        SMALLINT DEFAULT 1,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted       SMALLINT DEFAULT 0
);

-- Inventory 表由 InventoryDatabaseInitializer 创建（与 Inventory 实体完全对齐，使用 inventory_id 主键列名）
-- 此处不再重复定义，避免 schema.sql 与 Initializer 的列名冲突（ID vs inventory_id）

-- Inventory warning 表由 InventoryDatabaseInitializer 创建（含 safe_stock 列，与实体对齐）
-- 此处不再重复定义，避免 SAFETY_STOCK vs safe_stock 列名冲突

-- Inventory log table
CREATE TABLE IF NOT EXISTS INVENTORY_LOG (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INVENTORY_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    WAREHOUSE_NAME VARCHAR(50) NOT NULL,
    TYPE SMALLINT NOT NULL,
    BEFORE_STOCK INT NOT NULL,
    AFTER_STOCK INT NOT NULL,
    CHANGE_QUANTITY INT NOT NULL,
    OPERATOR_ID BIGINT,
    OPERATOR_NAME VARCHAR(50),
    REMARK VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0
);

-- Inventory loss table
CREATE TABLE IF NOT EXISTS INVENTORY_LOSS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    WAREHOUSE_NAME VARCHAR(50) NOT NULL,
    LOSS_QUANTITY INT NOT NULL,
    LOSS_REASON VARCHAR(200) NOT NULL,
    LOSS_DATE TIMESTAMP NOT NULL,
    STATUS SMALLINT DEFAULT 1,
    CREATED_BY BIGINT,
    CREATED_NAME VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0
);

-- Inventory transfer table
CREATE TABLE IF NOT EXISTS INVENTORY_TRANSFER (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    FROM_WAREHOUSE_ID BIGINT NOT NULL,
    FROM_WAREHOUSE_NAME VARCHAR(50) NOT NULL,
    TO_WAREHOUSE_ID BIGINT NOT NULL,
    TO_WAREHOUSE_NAME VARCHAR(50) NOT NULL,
    TRANSFER_QUANTITY INT NOT NULL,
    TRANSFER_REASON VARCHAR(200),
    TRANSFER_DATE TIMESTAMP NOT NULL,
    STATUS SMALLINT DEFAULT 1,
    CREATED_BY BIGINT,
    CREATED_NAME VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0
);

-- Inventory check table
CREATE TABLE IF NOT EXISTS INVENTORY_CHECK (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CHECK_CODE VARCHAR(50) NOT NULL UNIQUE,
    WAREHOUSE_ID BIGINT NOT NULL,
    WAREHOUSE_NAME VARCHAR(50) NOT NULL,
    CHECK_DATE TIMESTAMP NOT NULL,
    CHECK_PERSON_ID BIGINT,
    CHECK_PERSON_NAME VARCHAR(50),
    STATUS SMALLINT DEFAULT 1,
    TOTAL_PRODUCTS INT DEFAULT 0,
    DIFFERENCE_PRODUCTS INT DEFAULT 0,
    TOTAL_DIFFERENCE_QUANTITY INT DEFAULT 0,
    REMARK VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0
);

-- Inventory check detail table
CREATE TABLE IF NOT EXISTS INVENTORY_CHECK_DETAIL (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CHECK_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    SYSTEM_STOCK INT NOT NULL,
    ACTUAL_STOCK INT NOT NULL,
    DIFFERENCE_QUANTITY INT NOT NULL,
    DIFFERENCE_REASON VARCHAR(200),
    STATUS SMALLINT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0
);

-- Warehouse table
CREATE TABLE IF NOT EXISTS WAREHOUSE (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    TYPE VARCHAR(20) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    MANAGER VARCHAR(20) NOT NULL,
    STATUS SMALLINT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Insert default data

-- Insert default roles
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME, DESCRIPTION, ROLE_TYPE, LEVEL, STATUS, IS_SYSTEM) VALUES
('admin', 'Super Admin', 'System super admin, has all permissions', 1, 999, 1, 1),
('user', 'Normal User', 'System normal user, has basic permissions', 1, 1, 1, 1);

-- Insert default permissions (menu permissions)
INSERT INTO PERMISSIONS (PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, MODULE, PARENT_ID, LEVEL, SORT_ORDER, STATUS, ICON, PATH, COMPONENT) VALUES
('system', 'System Management', 1, 'system', 0, 1, 1, 1, 'system', '/system', 'Layout');

INSERT INTO PERMISSIONS (PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, MODULE, PARENT_ID, LEVEL, SORT_ORDER, STATUS, ICON, PATH, COMPONENT) VALUES
('user_manage', 'User Management', 1, 'system', 1, 2, 1, 1, 'user', 'user', 'system/user/index'),
('role_manage', 'Role Management', 1, 'system', 1, 2, 2, 1, 'peoples', 'role', 'system/role/index'),
('permission_manage', 'Permission Management', 1, 'system', 1, 2, 3, 1, 'tree-table', 'permission', 'system/permission/index'),
('dept_manage', 'Department Management', 1, 'system', 1, 2, 4, 1, 'tree', 'dept', 'system/dept/index');

-- Insert promotion-related permissions
INSERT INTO PERMISSIONS (PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, MODULE, PARENT_ID, LEVEL, SORT_ORDER, STATUS, ICON, PATH, COMPONENT) VALUES
('promotion', 'Promotion Management', 1, 'promotion', 0, 1, 10, 1, 'promotion', '/promotion', 'Layout');

INSERT INTO PERMISSIONS (PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, MODULE, PARENT_ID, LEVEL, SORT_ORDER, STATUS, ICON, PATH, COMPONENT) VALUES
('promotion_manage', 'Promotion Activity Management', 1, 'promotion', 6, 2, 1, 1, 'promotion', 'promotion', 'promotion/index');

-- Insert promotion-related button permissions
INSERT INTO PERMISSIONS (PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, MODULE, PARENT_ID, LEVEL, SORT_ORDER, STATUS) VALUES
('promotion_add', 'Add Activity', 2, 'promotion', 7, 3, 1, 1),
('promotion_edit', 'Edit Activity', 2, 'promotion', 7, 3, 2, 1),
('promotion_delete', 'Delete Activity', 2, 'promotion', 7, 3, 3, 1);

-- Order table
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID VARCHAR(32) PRIMARY KEY,
    USER_ID VARCHAR(32),
    ORDER_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    ORDER_TYPE SMALLINT DEFAULT 0,
    ORDER_STATUS SMALLINT DEFAULT 0,
    ORDER_AMOUNT DECIMAL(10,2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10,2) DEFAULT 0.00,
    ACTUAL_AMOUNT DECIMAL(10,2) NOT NULL,
    PAYMENT_METHOD SMALLINT,
    PAYMENT_TIME TIMESTAMP,
    DELIVERY_ADDRESS VARCHAR(255),
    CONTACT_NAME VARCHAR(50),
    CONTACT_PHONE VARCHAR(20),
    REMARKS TEXT,
    ORDER_SOURCE SMALLINT DEFAULT 0,
    MERCHANT_ID VARCHAR(32),
    DELIVERYMAN_ID VARCHAR(32),
    ESTIMATED_DELIVERY_TIME TIMESTAMP,
    ACTUAL_DELIVERY_TIME TIMESTAMP,
    CANCEL_REASON VARCHAR(255),
    REFUND_REASON VARCHAR(255),
    REFUND_AMOUNT DECIMAL(10,2) DEFAULT 0.00,
    REFUND_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(50),
    UPDATE_BY VARCHAR(50),
    DELETED SMALLINT DEFAULT 0
);

-- Create order table indexes
CREATE INDEX IDX_ORDERS_USER_ID ON ORDERS(USER_ID);
CREATE INDEX IDX_ORDERS_ORDER_NUMBER ON ORDERS(ORDER_NUMBER);
CREATE INDEX IDX_ORDERS_ORDER_STATUS ON ORDERS(ORDER_STATUS);
CREATE INDEX IDX_ORDERS_CREATE_TIME ON ORDERS(CREATE_TIME);
CREATE INDEX IDX_ORDERS_DELETED ON ORDERS(DELETED);

-- Order item table
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_ID VARCHAR(32) PRIMARY KEY,
    ORDER_ID VARCHAR(32) NOT NULL,
    FOOD_ID VARCHAR(32) NOT NULL,
    FOOD_NAME VARCHAR(100) NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    QUANTITY INT NOT NULL,
    SUBTOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    FOOD_IMAGE_URL VARCHAR(255),
    SPECIFICATION VARCHAR(100),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED SMALLINT DEFAULT 0,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE
);

-- Create order item table indexes
CREATE INDEX IDX_ORDER_ITEMS_ORDER_ID ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_FOOD_ID ON ORDER_ITEMS(FOOD_ID);
CREATE INDEX IDX_ORDER_ITEMS_DELETED ON ORDER_ITEMS(DELETED);

-- Other inbound table (其他入库表)
CREATE TABLE IF NOT EXISTS OTHER_INBOUND (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INBOUND_NO VARCHAR(50) NOT NULL UNIQUE,
    INBOUND_TYPE VARCHAR(20) NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT VARCHAR(20),
    WAREHOUSE_ID BIGINT NOT NULL,
    WAREHOUSE_NAME VARCHAR(100),
    INBOUND_TIME TIMESTAMP NOT NULL,
    OPERATOR_ID BIGINT,
    OPERATOR_NAME VARCHAR(50),
    SOURCE_ID BIGINT,
    RETURN_SOURCE VARCHAR(20),
    REMARK VARCHAR(500),
    STATUS SMALLINT DEFAULT 1,
    DELETED SMALLINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create other inbound table indexes
CREATE INDEX IDX_OTHER_INBOUND_NO ON OTHER_INBOUND(INBOUND_NO);
CREATE INDEX IDX_OTHER_INBOUND_PRODUCT_ID ON OTHER_INBOUND(PRODUCT_ID);
CREATE INDEX IDX_OTHER_INBOUND_WAREHOUSE_ID ON OTHER_INBOUND(WAREHOUSE_ID);
CREATE INDEX IDX_OTHER_INBOUND_TIME ON OTHER_INBOUND(INBOUND_TIME);
CREATE INDEX IDX_OTHER_INBOUND_DELETED ON OTHER_INBOUND(DELETED);

-- Loss outbound table (报损出库表)
CREATE TABLE IF NOT EXISTS LOSS_OUTBOUND (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOSS_NO VARCHAR(50) NOT NULL UNIQUE,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    LOSS_QUANTITY INT NOT NULL,
    UNIT VARCHAR(20),
    LOSS_REASON VARCHAR(50) NOT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    WAREHOUSE_NAME VARCHAR(100),
    LOSS_DATE DATE NOT NULL,
    LOSS_AMOUNT DECIMAL(10,2),
    STATUS VARCHAR(20) DEFAULT 'pending',
    OPERATOR_ID BIGINT,
    OPERATOR_NAME VARCHAR(50),
    APPROVER_ID BIGINT,
    APPROVER_NAME VARCHAR(50),
    APPROVE_TIME TIMESTAMP,
    REMARK VARCHAR(500),
    DELETED SMALLINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create loss outbound table indexes
CREATE INDEX IDX_LOSS_OUTBOUND_NO ON LOSS_OUTBOUND(LOSS_NO);
CREATE INDEX IDX_LOSS_OUTBOUND_PRODUCT_ID ON LOSS_OUTBOUND(PRODUCT_ID);
CREATE INDEX IDX_LOSS_OUTBOUND_WAREHOUSE_ID ON LOSS_OUTBOUND(WAREHOUSE_ID);
CREATE INDEX IDX_LOSS_OUTBOUND_STATUS ON LOSS_OUTBOUND(STATUS);
CREATE INDEX IDX_LOSS_OUTBOUND_DATE ON LOSS_OUTBOUND(LOSS_DATE);
CREATE INDEX IDX_LOSS_OUTBOUND_DELETED ON LOSS_OUTBOUND(DELETED);

-- ============================================
-- Food categories table
-- 对应实体: FoodCategoryNew, 由 FoodManagement 页面 /v1/product-center/categories 调用
-- ============================================
CREATE TABLE IF NOT EXISTS food_categories (
    category_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    parent_id BIGINT DEFAULT 0,
    icon_url VARCHAR(255),
    sort_order INT DEFAULT 0,
    status INT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE INDEX IDX_FOOD_CATEGORIES_NAME ON food_categories(category_name);
CREATE INDEX IDX_FOOD_CATEGORIES_PARENT_ID ON food_categories(parent_id);
CREATE INDEX IDX_FOOD_CATEGORIES_STATUS ON food_categories(status);
CREATE INDEX IDX_FOOD_CATEGORIES_DELETED ON food_categories(deleted);

-- ============================================
-- Foods table
-- 对应实体: FoodNew, 由 FoodManagement 页面 /v1/product-center/foods 调用
-- ============================================
CREATE TABLE IF NOT EXISTS foods (
    food_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    food_code VARCHAR(50) UNIQUE,
    food_name VARCHAR(100) NOT NULL,
    category_id BIGINT,
    specification VARCHAR(50),
    unit VARCHAR(20),
    sale_price BIGINT,
    cost_price BIGINT,
    stock INT,
    min_stock INT,
    image_url VARCHAR(255),
    description TEXT,
    cooking_time INT,
    status INT DEFAULT 1,
    is_recommend BOOLEAN DEFAULT FALSE,
    is_spicy BOOLEAN DEFAULT FALSE,
    sort_order INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INT DEFAULT 0,
    version INT DEFAULT 0
);

CREATE INDEX IDX_FOODS_CODE ON foods(food_code);
CREATE INDEX IDX_FOODS_NAME ON foods(food_name);
CREATE INDEX IDX_FOODS_CATEGORY_ID ON foods(category_id);
CREATE INDEX IDX_FOODS_STATUS ON foods(status);
CREATE INDEX IDX_FOODS_DELETED ON foods(deleted);

-- Insert default food categories
-- 注意: ON CONFLICT 必须指定冲突列（依赖 V20260710_001 创建的部分唯一索引）
INSERT INTO food_categories (category_name, parent_id, sort_order, status) VALUES
('热菜', 0, 1, 1),
('凉菜', 0, 2, 1),
('汤类', 0, 3, 1),
('主食', 0, 4, 1),
('饮品', 0, 5, 1)
ON CONFLICT (category_name, parent_id) WHERE deleted = 0 DO NOTHING;

-- Insert sample foods
INSERT INTO foods (food_code, food_name, category_id, unit, sale_price, cost_price, stock, min_stock, status, is_recommend, sort_order) VALUES
('FD001', '红烧肉', 1, '份', 3800, 1500, 100, 10, 1, TRUE, 1),
('FD002', '宫保鸡丁', 1, '份', 3200, 1200, 100, 10, 1, TRUE, 2),
('FD003', '鱼香肉丝', 1, '份', 2800, 1000, 100, 10, 1, FALSE, 3),
('FD004', '凉拌黄瓜', 2, '份', 1200, 300, 100, 10, 1, FALSE, 1),
('FD005', '番茄蛋汤', 3, '碗', 1500, 400, 100, 10, 1, FALSE, 1)
ON CONFLICT DO NOTHING;

-- ============================================
-- Health certificate table
-- 对应实体: HealthCertificate, 由 StoreCertificate 页面 /v1/store/health-certificate 调用
-- ============================================
CREATE TABLE IF NOT EXISTS health_certificate (
    id VARCHAR(32) PRIMARY KEY,
    employee_id VARCHAR(32),
    employee_name VARCHAR(100),
    store VARCHAR(100),
    store_id VARCHAR(32),
    store_name VARCHAR(100),
    certificate_number VARCHAR(100),
    issue_date DATE,
    expiry_date DATE,
    status VARCHAR(20) DEFAULT 'valid',
    issuer VARCHAR(200),
    note VARCHAR(500),
    expense_status VARCHAR(20) DEFAULT 'pending',
    approval_status VARCHAR(20) DEFAULT 'draft',
    approval_by VARCHAR(100),
    approval_date DATE,
    reject_reason VARCHAR(500),
    submission_date DATE,
    submitted_by VARCHAR(100),
    certificate_image VARCHAR(500),
    last_expense_id BIGINT,
    operator VARCHAR(100),
    operation_time DATE,
    expiry_days INT,
    deleted BOOLEAN DEFAULT FALSE,
    deleted_at DATE,
    deleted_by VARCHAR(100)
);

CREATE INDEX IDX_HEALTH_CERT_EMPLOYEE_ID ON health_certificate(employee_id);
CREATE INDEX IDX_HEALTH_CERT_STORE_ID ON health_certificate(store_id);
CREATE INDEX IDX_HEALTH_CERT_STATUS ON health_certificate(status);
CREATE INDEX IDX_HEALTH_CERT_EXPIRY_DATE ON health_certificate(expiry_date);
CREATE INDEX IDX_HEALTH_CERT_DELETED ON health_certificate(deleted);

-- Insert sample health certificates
INSERT INTO health_certificate (id, employee_id, employee_name, store_id, store_name, certificate_number, issue_date, expiry_date, status, issuer, approval_status, submission_date, submitted_by, deleted) VALUES
('HC001', '1', '系统管理员', '1', '总店', 'HCA202601001', '2025-07-15', '2026-07-15', 'valid', '市卫健委', 'approved', '2025-07-15', 'admin', FALSE),
('HC002', '2', '店长测试账号', '1', '总店', 'HCA202601002', '2025-06-01', '2026-06-01', 'expiring', '市卫健委', 'approved', '2025-06-01', 'admin', FALSE),
('HC003', '3', '采购员测试账号', '1', '总店', 'HCA202601003', '2024-12-01', '2025-12-01', 'expired', '市卫健委', 'approved', '2024-12-01', 'admin', FALSE)
ON CONFLICT DO NOTHING;

-- Health certificate expense table (HealthCertificateExpense entity)
CREATE TABLE IF NOT EXISTS health_certificate_expense (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    health_certificate_id VARCHAR(32),
    employee_id VARCHAR(32),
    employee_name VARCHAR(100),
    store VARCHAR(100),
    amount DOUBLE,
    invoice_type VARCHAR(50),
    invoice_number VARCHAR(100),
    invoice_date DATE,
    invoice_attachments TEXT,
    reason VARCHAR(500),
    note VARCHAR(500),
    status VARCHAR(20) DEFAULT 'pending',
    apply_date DATE,
    approve_date DATE,
    reimburse_date DATE,
    reject_reason VARCHAR(500),
    expense_type VARCHAR(20),
    approval_history TEXT,
    creator VARCHAR(100),
    create_time DATE DEFAULT CURRENT_DATE,
    updater VARCHAR(100),
    update_time DATE DEFAULT CURRENT_DATE,
    payment_retry_count INT DEFAULT 0,
    payment_status VARCHAR(20) DEFAULT 'pending',
    payment_method VARCHAR(20),
    payment_transaction_id VARCHAR(100)
);

CREATE INDEX IDX_HEALTH_CERT_EXPENSE_HC_ID ON health_certificate_expense(health_certificate_id);
CREATE INDEX IDX_HEALTH_CERT_EXPENSE_EMP_ID ON health_certificate_expense(employee_id);
CREATE INDEX IDX_HEALTH_CERT_EXPENSE_STATUS ON health_certificate_expense(status);
CREATE INDEX IDX_HEALTH_CERT_EXPENSE_CREATE_TIME ON health_certificate_expense(create_time);

-- Insert sample expense records
INSERT INTO health_certificate_expense (health_certificate_id, employee_id, employee_name, store, amount, invoice_type, invoice_number, invoice_date, reason, status, apply_date, expense_type, creator, create_time) VALUES
('HC001', '1', '系统管理员', '总店', 120.00, '普通发票', 'INV202601001', '2025-07-15', '健康证办理费用', 'reimbursed', '2025-07-15', 'new', 'admin', '2025-07-15'),
('HC002', '2', '店长测试账号', '总店', 80.00, '普通发票', 'INV202601002', '2025-06-01', '健康证续期费用', 'approved', '2025-06-01', 'renewal', 'admin', '2025-06-01'),
('HC003', '3', '采购员测试账号', '总店', 150.00, '增值税发票', 'INV202601003', '2024-12-01', '健康证换证费用', 'pending', '2024-12-01', 'new', 'admin', '2024-12-01')
ON CONFLICT DO NOTHING;